# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ConsumptionModel Class
#'
#' @field modelType 
#' @field generalInformation 
#' @field scope 
#' @field dataBackground 
#' @field modelMath 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ConsumptionModel <- R6::R6Class(
  'ConsumptionModel',
  public = list(
    `modelType` = NULL,
    `generalInformation` = NULL,
    `scope` = NULL,
    `dataBackground` = NULL,
    `modelMath` = NULL,
    initialize = function(`modelType`, `generalInformation`, `scope`, `dataBackground`, `modelMath`){
      if (!missing(`modelType`)) {
        stopifnot(is.character(`modelType`), length(`modelType`) == 1)
        self$`modelType` <- `modelType`
      }
      if (!missing(`generalInformation`)) {
        stopifnot(R6::is.R6(`generalInformation`))
        self$`generalInformation` <- `generalInformation`
      }
      if (!missing(`scope`)) {
        stopifnot(R6::is.R6(`scope`))
        self$`scope` <- `scope`
      }
      if (!missing(`dataBackground`)) {
        stopifnot(R6::is.R6(`dataBackground`))
        self$`dataBackground` <- `dataBackground`
      }
      if (!missing(`modelMath`)) {
        stopifnot(R6::is.R6(`modelMath`))
        self$`modelMath` <- `modelMath`
      }
    },
    toJSON = function() {
      ConsumptionModelObject <- list()
      if (!is.null(self$`modelType`)) {
        ConsumptionModelObject[['modelType']] <- self$`modelType`
      }
      if (!is.null(self$`generalInformation`)) {
        ConsumptionModelObject[['generalInformation']] <- self$`generalInformation`$toJSON()
      }
      if (!is.null(self$`scope`)) {
        ConsumptionModelObject[['scope']] <- self$`scope`$toJSON()
      }
      if (!is.null(self$`dataBackground`)) {
        ConsumptionModelObject[['dataBackground']] <- self$`dataBackground`$toJSON()
      }
      if (!is.null(self$`modelMath`)) {
        ConsumptionModelObject[['modelMath']] <- self$`modelMath`$toJSON()
      }

      ConsumptionModelObject
    },
    fromJSON = function(ConsumptionModelJson) {
      ConsumptionModelObject <- jsonlite::fromJSON(ConsumptionModelJson)
      if (!is.null(ConsumptionModelObject$`modelType`)) {
        self$`modelType` <- ConsumptionModelObject$`modelType`
      }
      if (!is.null(ConsumptionModelObject$`generalInformation`)) {
        generalInformationObject <- PredictiveModelGeneralInformation$new()
        generalInformationObject$fromJSON(jsonlite::toJSON(ConsumptionModelObject$generalInformation, auto_unbox = TRUE))
        self$`generalInformation` <- generalInformationObject
      }
      if (!is.null(ConsumptionModelObject$`scope`)) {
        scopeObject <- ConsumptionModelScope$new()
        scopeObject$fromJSON(jsonlite::toJSON(ConsumptionModelObject$scope, auto_unbox = TRUE))
        self$`scope` <- scopeObject
      }
      if (!is.null(ConsumptionModelObject$`dataBackground`)) {
        dataBackgroundObject <- GenericModelDataBackground$new()
        dataBackgroundObject$fromJSON(jsonlite::toJSON(ConsumptionModelObject$dataBackground, auto_unbox = TRUE))
        self$`dataBackground` <- dataBackgroundObject
      }
      if (!is.null(ConsumptionModelObject$`modelMath`)) {
        modelMathObject <- PredictiveModelModelMath$new()
        modelMathObject$fromJSON(jsonlite::toJSON(ConsumptionModelObject$modelMath, auto_unbox = TRUE))
        self$`modelMath` <- modelMathObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "modelType": %s,
           "generalInformation": %s,
           "scope": %s,
           "dataBackground": %s,
           "modelMath": %s
        }',
        self$`modelType`,
        self$`generalInformation`$toJSON(),
        self$`scope`$toJSON(),
        self$`dataBackground`$toJSON(),
        self$`modelMath`$toJSON()
      )
    },
    fromJSONString = function(ConsumptionModelJson) {
      ConsumptionModelObject <- jsonlite::fromJSON(ConsumptionModelJson)
      self$`modelType` <- ConsumptionModelObject$`modelType`
      PredictiveModelGeneralInformationObject <- PredictiveModelGeneralInformation$new()
      self$`generalInformation` <- PredictiveModelGeneralInformationObject$fromJSON(jsonlite::toJSON(ConsumptionModelObject$generalInformation, auto_unbox = TRUE))
      ConsumptionModelScopeObject <- ConsumptionModelScope$new()
      self$`scope` <- ConsumptionModelScopeObject$fromJSON(jsonlite::toJSON(ConsumptionModelObject$scope, auto_unbox = TRUE))
      GenericModelDataBackgroundObject <- GenericModelDataBackground$new()
      self$`dataBackground` <- GenericModelDataBackgroundObject$fromJSON(jsonlite::toJSON(ConsumptionModelObject$dataBackground, auto_unbox = TRUE))
      PredictiveModelModelMathObject <- PredictiveModelModelMath$new()
      self$`modelMath` <- PredictiveModelModelMathObject$fromJSON(jsonlite::toJSON(ConsumptionModelObject$modelMath, auto_unbox = TRUE))
    }
  )
)
