# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ConsumptionModelScope Class
#'
#' @field product 
#' @field populationGroup 
#' @field generalComment 
#' @field temporalInformation 
#' @field spatialInformation 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ConsumptionModelScope <- R6::R6Class(
  'ConsumptionModelScope',
  public = list(
    `product` = NULL,
    `populationGroup` = NULL,
    `generalComment` = NULL,
    `temporalInformation` = NULL,
    `spatialInformation` = NULL,
    initialize = function(`product`, `populationGroup`, `generalComment`, `temporalInformation`, `spatialInformation`){
      if (!missing(`product`)) {
        stopifnot(is.list(`product`), length(`product`) != 0)
        lapply(`product`, function(x) stopifnot(R6::is.R6(x)))
        self$`product` <- `product`
      }
      if (!missing(`populationGroup`)) {
        stopifnot(is.list(`populationGroup`), length(`populationGroup`) != 0)
        lapply(`populationGroup`, function(x) stopifnot(R6::is.R6(x)))
        self$`populationGroup` <- `populationGroup`
      }
      if (!missing(`generalComment`)) {
        stopifnot(is.character(`generalComment`), length(`generalComment`) == 1)
        self$`generalComment` <- `generalComment`
      }
      if (!missing(`temporalInformation`)) {
        stopifnot(is.character(`temporalInformation`), length(`temporalInformation`) == 1)
        self$`temporalInformation` <- `temporalInformation`
      }
      if (!missing(`spatialInformation`)) {
        stopifnot(is.list(`spatialInformation`), length(`spatialInformation`) != 0)
        lapply(`spatialInformation`, function(x) stopifnot(is.character(x)))
        self$`spatialInformation` <- `spatialInformation`
      }
    },
    toJSON = function() {
      ConsumptionModelScopeObject <- list()
      if (!is.null(self$`product`)) {
        ConsumptionModelScopeObject[['product']] <- lapply(self$`product`, function(x) x$toJSON())
      }
      if (!is.null(self$`populationGroup`)) {
        ConsumptionModelScopeObject[['populationGroup']] <- lapply(self$`populationGroup`, function(x) x$toJSON())
      }
      if (!is.null(self$`generalComment`)) {
        ConsumptionModelScopeObject[['generalComment']] <- self$`generalComment`
      }
      if (!is.null(self$`temporalInformation`)) {
        ConsumptionModelScopeObject[['temporalInformation']] <- self$`temporalInformation`
      }
      if (!is.null(self$`spatialInformation`)) {
        ConsumptionModelScopeObject[['spatialInformation']] <- self$`spatialInformation`
      }

      ConsumptionModelScopeObject
    },
    fromJSON = function(ConsumptionModelScopeJson) {
      ConsumptionModelScopeObject <- jsonlite::fromJSON(ConsumptionModelScopeJson)
      if (!is.null(ConsumptionModelScopeObject$`product`)) {
        self$`product` <- lapply(ConsumptionModelScopeObject$`product`, function(x) {
          productObject <- Product$new()
          productObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          productObject
        })
      }
      if (!is.null(ConsumptionModelScopeObject$`populationGroup`)) {
        self$`populationGroup` <- lapply(ConsumptionModelScopeObject$`populationGroup`, function(x) {
          populationGroupObject <- PopulationGroup$new()
          populationGroupObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          populationGroupObject
        })
      }
      if (!is.null(ConsumptionModelScopeObject$`generalComment`)) {
        self$`generalComment` <- ConsumptionModelScopeObject$`generalComment`
      }
      if (!is.null(ConsumptionModelScopeObject$`temporalInformation`)) {
        self$`temporalInformation` <- ConsumptionModelScopeObject$`temporalInformation`
      }
      if (!is.null(ConsumptionModelScopeObject$`spatialInformation`)) {
        self$`spatialInformation` <- ConsumptionModelScopeObject$`spatialInformation`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "product": [%s],
           "populationGroup": [%s],
           "generalComment": %s,
           "temporalInformation": %s,
           "spatialInformation": [%s]
        }',
        lapply(self$`product`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`populationGroup`, function(x) paste(x$toJSON(), sep=",")),
        self$`generalComment`,
        self$`temporalInformation`,
        lapply(self$`spatialInformation`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(ConsumptionModelScopeJson) {
      ConsumptionModelScopeObject <- jsonlite::fromJSON(ConsumptionModelScopeJson)
      self$`product` <- lapply(ConsumptionModelScopeObject$`product`, function(x) Product$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`populationGroup` <- lapply(ConsumptionModelScopeObject$`populationGroup`, function(x) PopulationGroup$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`generalComment` <- ConsumptionModelScopeObject$`generalComment`
      self$`temporalInformation` <- ConsumptionModelScopeObject$`temporalInformation`
      self$`spatialInformation` <- ConsumptionModelScopeObject$`spatialInformation`
    }
  )
)
