# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Contact Class
#'
#' @field title 
#' @field familyName 
#' @field givenName 
#' @field email 
#' @field telephone 
#' @field streetAddress 
#' @field country 
#' @field zipCode 
#' @field region 
#' @field timeZone 
#' @field gender 
#' @field note 
#' @field organization 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Contact <- R6::R6Class(
  'Contact',
  public = list(
    `title` = NULL,
    `familyName` = NULL,
    `givenName` = NULL,
    `email` = NULL,
    `telephone` = NULL,
    `streetAddress` = NULL,
    `country` = NULL,
    `zipCode` = NULL,
    `region` = NULL,
    `timeZone` = NULL,
    `gender` = NULL,
    `note` = NULL,
    `organization` = NULL,
    initialize = function(`title`, `familyName`, `givenName`, `email`, `telephone`, `streetAddress`, `country`, `zipCode`, `region`, `timeZone`, `gender`, `note`, `organization`){
      if (!missing(`title`)) {
        stopifnot(is.list(`title`), length(`title`) != 0)
        lapply(`title`, function(x) stopifnot(is.character(x)))
        self$`title` <- `title`
      }
      if (!missing(`familyName`)) {
        stopifnot(is.list(`familyName`), length(`familyName`) != 0)
        lapply(`familyName`, function(x) stopifnot(is.character(x)))
        self$`familyName` <- `familyName`
      }
      if (!missing(`givenName`)) {
        stopifnot(is.list(`givenName`), length(`givenName`) != 0)
        lapply(`givenName`, function(x) stopifnot(is.character(x)))
        self$`givenName` <- `givenName`
      }
      if (!missing(`email`)) {
        stopifnot(is.character(`email`), length(`email`) == 1)
        self$`email` <- `email`
      }
      if (!missing(`telephone`)) {
        stopifnot(is.list(`telephone`), length(`telephone`) != 0)
        lapply(`telephone`, function(x) stopifnot(is.character(x)))
        self$`telephone` <- `telephone`
      }
      if (!missing(`streetAddress`)) {
        stopifnot(is.list(`streetAddress`), length(`streetAddress`) != 0)
        lapply(`streetAddress`, function(x) stopifnot(is.character(x)))
        self$`streetAddress` <- `streetAddress`
      }
      if (!missing(`country`)) {
        stopifnot(is.list(`country`), length(`country`) != 0)
        lapply(`country`, function(x) stopifnot(is.character(x)))
        self$`country` <- `country`
      }
      if (!missing(`zipCode`)) {
        stopifnot(is.list(`zipCode`), length(`zipCode`) != 0)
        lapply(`zipCode`, function(x) stopifnot(is.character(x)))
        self$`zipCode` <- `zipCode`
      }
      if (!missing(`region`)) {
        stopifnot(is.list(`region`), length(`region`) != 0)
        lapply(`region`, function(x) stopifnot(is.character(x)))
        self$`region` <- `region`
      }
      if (!missing(`timeZone`)) {
        stopifnot(is.list(`timeZone`), length(`timeZone`) != 0)
        lapply(`timeZone`, function(x) stopifnot(is.character(x)))
        self$`timeZone` <- `timeZone`
      }
      if (!missing(`gender`)) {
        stopifnot(is.list(`gender`), length(`gender`) != 0)
        lapply(`gender`, function(x) stopifnot(is.character(x)))
        self$`gender` <- `gender`
      }
      if (!missing(`note`)) {
        stopifnot(is.list(`note`), length(`note`) != 0)
        lapply(`note`, function(x) stopifnot(is.character(x)))
        self$`note` <- `note`
      }
      if (!missing(`organization`)) {
        stopifnot(is.list(`organization`), length(`organization`) != 0)
        lapply(`organization`, function(x) stopifnot(is.character(x)))
        self$`organization` <- `organization`
      }
    },
    toJSON = function() {
      ContactObject <- list()
      if (!is.null(self$`title`)) {
        ContactObject[['title']] <- self$`title`
      }
      if (!is.null(self$`familyName`)) {
        ContactObject[['familyName']] <- self$`familyName`
      }
      if (!is.null(self$`givenName`)) {
        ContactObject[['givenName']] <- self$`givenName`
      }
      if (!is.null(self$`email`)) {
        ContactObject[['email']] <- self$`email`
      }
      if (!is.null(self$`telephone`)) {
        ContactObject[['telephone']] <- self$`telephone`
      }
      if (!is.null(self$`streetAddress`)) {
        ContactObject[['streetAddress']] <- self$`streetAddress`
      }
      if (!is.null(self$`country`)) {
        ContactObject[['country']] <- self$`country`
      }
      if (!is.null(self$`zipCode`)) {
        ContactObject[['zipCode']] <- self$`zipCode`
      }
      if (!is.null(self$`region`)) {
        ContactObject[['region']] <- self$`region`
      }
      if (!is.null(self$`timeZone`)) {
        ContactObject[['timeZone']] <- self$`timeZone`
      }
      if (!is.null(self$`gender`)) {
        ContactObject[['gender']] <- self$`gender`
      }
      if (!is.null(self$`note`)) {
        ContactObject[['note']] <- self$`note`
      }
      if (!is.null(self$`organization`)) {
        ContactObject[['organization']] <- self$`organization`
      }

      ContactObject
    },
    fromJSON = function(ContactJson) {
      ContactObject <- jsonlite::fromJSON(ContactJson)
      if (!is.null(ContactObject$`title`)) {
        self$`title` <- ContactObject$`title`
      }
      if (!is.null(ContactObject$`familyName`)) {
        self$`familyName` <- ContactObject$`familyName`
      }
      if (!is.null(ContactObject$`givenName`)) {
        self$`givenName` <- ContactObject$`givenName`
      }
      if (!is.null(ContactObject$`email`)) {
        self$`email` <- ContactObject$`email`
      }
      if (!is.null(ContactObject$`telephone`)) {
        self$`telephone` <- ContactObject$`telephone`
      }
      if (!is.null(ContactObject$`streetAddress`)) {
        self$`streetAddress` <- ContactObject$`streetAddress`
      }
      if (!is.null(ContactObject$`country`)) {
        self$`country` <- ContactObject$`country`
      }
      if (!is.null(ContactObject$`zipCode`)) {
        self$`zipCode` <- ContactObject$`zipCode`
      }
      if (!is.null(ContactObject$`region`)) {
        self$`region` <- ContactObject$`region`
      }
      if (!is.null(ContactObject$`timeZone`)) {
        self$`timeZone` <- ContactObject$`timeZone`
      }
      if (!is.null(ContactObject$`gender`)) {
        self$`gender` <- ContactObject$`gender`
      }
      if (!is.null(ContactObject$`note`)) {
        self$`note` <- ContactObject$`note`
      }
      if (!is.null(ContactObject$`organization`)) {
        self$`organization` <- ContactObject$`organization`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "title": [%s],
           "familyName": [%s],
           "givenName": [%s],
           "email": %s,
           "telephone": [%s],
           "streetAddress": [%s],
           "country": [%s],
           "zipCode": [%s],
           "region": [%s],
           "timeZone": [%s],
           "gender": [%s],
           "note": [%s],
           "organization": [%s]
        }',
        lapply(self$`title`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`familyName`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`givenName`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`email`,
        lapply(self$`telephone`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`streetAddress`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`country`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`zipCode`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`region`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`timeZone`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`gender`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`note`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`organization`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(ContactJson) {
      ContactObject <- jsonlite::fromJSON(ContactJson)
      self$`title` <- ContactObject$`title`
      self$`familyName` <- ContactObject$`familyName`
      self$`givenName` <- ContactObject$`givenName`
      self$`email` <- ContactObject$`email`
      self$`telephone` <- ContactObject$`telephone`
      self$`streetAddress` <- ContactObject$`streetAddress`
      self$`country` <- ContactObject$`country`
      self$`zipCode` <- ContactObject$`zipCode`
      self$`region` <- ContactObject$`region`
      self$`timeZone` <- ContactObject$`timeZone`
      self$`gender` <- ContactObject$`gender`
      self$`note` <- ContactObject$`note`
      self$`organization` <- ContactObject$`organization`
    }
  )
)
