# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' DataModelGeneralInformation Class
#'
#' @field name 
#' @field source 
#' @field identifier 
#' @field author 
#' @field creator 
#' @field creationDate 
#' @field modificationDate 
#' @field rights 
#' @field availability 
#' @field url 
#' @field format 
#' @field reference 
#' @field language 
#' @field status 
#' @field objective 
#' @field description 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DataModelGeneralInformation <- R6::R6Class(
  'DataModelGeneralInformation',
  public = list(
    `name` = NULL,
    `source` = NULL,
    `identifier` = NULL,
    `author` = NULL,
    `creator` = NULL,
    `creationDate` = NULL,
    `modificationDate` = NULL,
    `rights` = NULL,
    `availability` = NULL,
    `url` = NULL,
    `format` = NULL,
    `reference` = NULL,
    `language` = NULL,
    `status` = NULL,
    `objective` = NULL,
    `description` = NULL,
    initialize = function(`name`, `source`, `identifier`, `author`, `creator`, `creationDate`, `modificationDate`, `rights`, `availability`, `url`, `format`, `reference`, `language`, `status`, `objective`, `description`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`source`)) {
        stopifnot(is.character(`source`), length(`source`) == 1)
        self$`source` <- `source`
      }
      if (!missing(`identifier`)) {
        stopifnot(is.character(`identifier`), length(`identifier`) == 1)
        self$`identifier` <- `identifier`
      }
      if (!missing(`author`)) {
        stopifnot(is.list(`author`), length(`author`) != 0)
        lapply(`author`, function(x) stopifnot(R6::is.R6(x)))
        self$`author` <- `author`
      }
      if (!missing(`creator`)) {
        stopifnot(is.list(`creator`), length(`creator`) != 0)
        lapply(`creator`, function(x) stopifnot(R6::is.R6(x)))
        self$`creator` <- `creator`
      }
      if (!missing(`creationDate`)) {
        stopifnot(is.character(`creationDate`), length(`creationDate`) == 1)
        self$`creationDate` <- `creationDate`
      }
      if (!missing(`modificationDate`)) {
        stopifnot(is.list(`modificationDate`), length(`modificationDate`) != 0)
        lapply(`modificationDate`, function(x) stopifnot(is.character(x)))
        self$`modificationDate` <- `modificationDate`
      }
      if (!missing(`rights`)) {
        stopifnot(is.character(`rights`), length(`rights`) == 1)
        self$`rights` <- `rights`
      }
      if (!missing(`availability`)) {
        stopifnot(is.character(`availability`), length(`availability`) == 1)
        self$`availability` <- `availability`
      }
      if (!missing(`url`)) {
        stopifnot(is.character(`url`), length(`url`) == 1)
        self$`url` <- `url`
      }
      if (!missing(`format`)) {
        stopifnot(is.character(`format`), length(`format`) == 1)
        self$`format` <- `format`
      }
      if (!missing(`reference`)) {
        stopifnot(is.list(`reference`), length(`reference`) != 0)
        lapply(`reference`, function(x) stopifnot(R6::is.R6(x)))
        self$`reference` <- `reference`
      }
      if (!missing(`language`)) {
        stopifnot(is.character(`language`), length(`language`) == 1)
        self$`language` <- `language`
      }
      if (!missing(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
      if (!missing(`objective`)) {
        stopifnot(is.character(`objective`), length(`objective`) == 1)
        self$`objective` <- `objective`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
    },
    toJSON = function() {
      DataModelGeneralInformationObject <- list()
      if (!is.null(self$`name`)) {
        DataModelGeneralInformationObject[['name']] <- self$`name`
      }
      if (!is.null(self$`source`)) {
        DataModelGeneralInformationObject[['source']] <- self$`source`
      }
      if (!is.null(self$`identifier`)) {
        DataModelGeneralInformationObject[['identifier']] <- self$`identifier`
      }
      if (!is.null(self$`author`)) {
        DataModelGeneralInformationObject[['author']] <- lapply(self$`author`, function(x) x$toJSON())
      }
      if (!is.null(self$`creator`)) {
        DataModelGeneralInformationObject[['creator']] <- lapply(self$`creator`, function(x) x$toJSON())
      }
      if (!is.null(self$`creationDate`)) {
        DataModelGeneralInformationObject[['creationDate']] <- self$`creationDate`
      }
      if (!is.null(self$`modificationDate`)) {
        DataModelGeneralInformationObject[['modificationDate']] <- self$`modificationDate`
      }
      if (!is.null(self$`rights`)) {
        DataModelGeneralInformationObject[['rights']] <- self$`rights`
      }
      if (!is.null(self$`availability`)) {
        DataModelGeneralInformationObject[['availability']] <- self$`availability`
      }
      if (!is.null(self$`url`)) {
        DataModelGeneralInformationObject[['url']] <- self$`url`
      }
      if (!is.null(self$`format`)) {
        DataModelGeneralInformationObject[['format']] <- self$`format`
      }
      if (!is.null(self$`reference`)) {
        DataModelGeneralInformationObject[['reference']] <- lapply(self$`reference`, function(x) x$toJSON())
      }
      if (!is.null(self$`language`)) {
        DataModelGeneralInformationObject[['language']] <- self$`language`
      }
      if (!is.null(self$`status`)) {
        DataModelGeneralInformationObject[['status']] <- self$`status`
      }
      if (!is.null(self$`objective`)) {
        DataModelGeneralInformationObject[['objective']] <- self$`objective`
      }
      if (!is.null(self$`description`)) {
        DataModelGeneralInformationObject[['description']] <- self$`description`
      }

      DataModelGeneralInformationObject
    },
    fromJSON = function(DataModelGeneralInformationJson) {
      DataModelGeneralInformationObject <- jsonlite::fromJSON(DataModelGeneralInformationJson)
      if (!is.null(DataModelGeneralInformationObject$`name`)) {
        self$`name` <- DataModelGeneralInformationObject$`name`
      }
      if (!is.null(DataModelGeneralInformationObject$`source`)) {
        self$`source` <- DataModelGeneralInformationObject$`source`
      }
      if (!is.null(DataModelGeneralInformationObject$`identifier`)) {
        self$`identifier` <- DataModelGeneralInformationObject$`identifier`
      }
      if (!is.null(DataModelGeneralInformationObject$`author`)) {
        self$`author` <- lapply(DataModelGeneralInformationObject$`author`, function(x) {
          authorObject <- Contact$new()
          authorObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          authorObject
        })
      }
      if (!is.null(DataModelGeneralInformationObject$`creator`)) {
        self$`creator` <- lapply(DataModelGeneralInformationObject$`creator`, function(x) {
          creatorObject <- Contact$new()
          creatorObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          creatorObject
        })
      }
      if (!is.null(DataModelGeneralInformationObject$`creationDate`)) {
        self$`creationDate` <- DataModelGeneralInformationObject$`creationDate`
      }
      if (!is.null(DataModelGeneralInformationObject$`modificationDate`)) {
        self$`modificationDate` <- DataModelGeneralInformationObject$`modificationDate`
      }
      if (!is.null(DataModelGeneralInformationObject$`rights`)) {
        self$`rights` <- DataModelGeneralInformationObject$`rights`
      }
      if (!is.null(DataModelGeneralInformationObject$`availability`)) {
        self$`availability` <- DataModelGeneralInformationObject$`availability`
      }
      if (!is.null(DataModelGeneralInformationObject$`url`)) {
        self$`url` <- DataModelGeneralInformationObject$`url`
      }
      if (!is.null(DataModelGeneralInformationObject$`format`)) {
        self$`format` <- DataModelGeneralInformationObject$`format`
      }
      if (!is.null(DataModelGeneralInformationObject$`reference`)) {
        self$`reference` <- lapply(DataModelGeneralInformationObject$`reference`, function(x) {
          referenceObject <- Reference$new()
          referenceObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          referenceObject
        })
      }
      if (!is.null(DataModelGeneralInformationObject$`language`)) {
        self$`language` <- DataModelGeneralInformationObject$`language`
      }
      if (!is.null(DataModelGeneralInformationObject$`status`)) {
        self$`status` <- DataModelGeneralInformationObject$`status`
      }
      if (!is.null(DataModelGeneralInformationObject$`objective`)) {
        self$`objective` <- DataModelGeneralInformationObject$`objective`
      }
      if (!is.null(DataModelGeneralInformationObject$`description`)) {
        self$`description` <- DataModelGeneralInformationObject$`description`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "source": %s,
           "identifier": %s,
           "author": [%s],
           "creator": [%s],
           "creationDate": %s,
           "modificationDate": [%s],
           "rights": %s,
           "availability": %s,
           "url": %s,
           "format": %s,
           "reference": [%s],
           "language": %s,
           "status": %s,
           "objective": %s,
           "description": %s
        }',
        self$`name`,
        self$`source`,
        self$`identifier`,
        lapply(self$`author`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`creator`, function(x) paste(x$toJSON(), sep=",")),
        self$`creationDate`,
        lapply(self$`modificationDate`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`rights`,
        self$`availability`,
        self$`url`,
        self$`format`,
        lapply(self$`reference`, function(x) paste(x$toJSON(), sep=",")),
        self$`language`,
        self$`status`,
        self$`objective`,
        self$`description`
      )
    },
    fromJSONString = function(DataModelGeneralInformationJson) {
      DataModelGeneralInformationObject <- jsonlite::fromJSON(DataModelGeneralInformationJson)
      self$`name` <- DataModelGeneralInformationObject$`name`
      self$`source` <- DataModelGeneralInformationObject$`source`
      self$`identifier` <- DataModelGeneralInformationObject$`identifier`
      self$`author` <- lapply(DataModelGeneralInformationObject$`author`, function(x) Contact$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`creator` <- lapply(DataModelGeneralInformationObject$`creator`, function(x) Contact$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`creationDate` <- DataModelGeneralInformationObject$`creationDate`
      self$`modificationDate` <- DataModelGeneralInformationObject$`modificationDate`
      self$`rights` <- DataModelGeneralInformationObject$`rights`
      self$`availability` <- DataModelGeneralInformationObject$`availability`
      self$`url` <- DataModelGeneralInformationObject$`url`
      self$`format` <- DataModelGeneralInformationObject$`format`
      self$`reference` <- lapply(DataModelGeneralInformationObject$`reference`, function(x) Reference$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`language` <- DataModelGeneralInformationObject$`language`
      self$`status` <- DataModelGeneralInformationObject$`status`
      self$`objective` <- DataModelGeneralInformationObject$`objective`
      self$`description` <- DataModelGeneralInformationObject$`description`
    }
  )
)
