# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' DataModel Class
#'
#' @field modelType 
#' @field generalInformation 
#' @field scope 
#' @field dataBackground 
#' @field modelMath 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DataModel <- R6::R6Class(
  'DataModel',
  public = list(
    `modelType` = NULL,
    `generalInformation` = NULL,
    `scope` = NULL,
    `dataBackground` = NULL,
    `modelMath` = NULL,
    initialize = function(`modelType`, `generalInformation`, `scope`, `dataBackground`, `modelMath`){
      if (!missing(`modelType`)) {
        stopifnot(is.character(`modelType`), length(`modelType`) == 1)
        self$`modelType` <- `modelType`
      }
      if (!missing(`generalInformation`)) {
        stopifnot(R6::is.R6(`generalInformation`))
        self$`generalInformation` <- `generalInformation`
      }
      if (!missing(`scope`)) {
        stopifnot(R6::is.R6(`scope`))
        self$`scope` <- `scope`
      }
      if (!missing(`dataBackground`)) {
        stopifnot(R6::is.R6(`dataBackground`))
        self$`dataBackground` <- `dataBackground`
      }
      if (!missing(`modelMath`)) {
        stopifnot(R6::is.R6(`modelMath`))
        self$`modelMath` <- `modelMath`
      }
    },
    toJSON = function() {
      DataModelObject <- list()
      if (!is.null(self$`modelType`)) {
        DataModelObject[['modelType']] <- self$`modelType`
      }
      if (!is.null(self$`generalInformation`)) {
        DataModelObject[['generalInformation']] <- self$`generalInformation`$toJSON()
      }
      if (!is.null(self$`scope`)) {
        DataModelObject[['scope']] <- self$`scope`$toJSON()
      }
      if (!is.null(self$`dataBackground`)) {
        DataModelObject[['dataBackground']] <- self$`dataBackground`$toJSON()
      }
      if (!is.null(self$`modelMath`)) {
        DataModelObject[['modelMath']] <- self$`modelMath`$toJSON()
      }

      DataModelObject
    },
    fromJSON = function(DataModelJson) {
      DataModelObject <- jsonlite::fromJSON(DataModelJson)
      if (!is.null(DataModelObject$`modelType`)) {
        self$`modelType` <- DataModelObject$`modelType`
      }
      if (!is.null(DataModelObject$`generalInformation`)) {
        generalInformationObject <- DataModelGeneralInformation$new()
        generalInformationObject$fromJSON(jsonlite::toJSON(DataModelObject$generalInformation, auto_unbox = TRUE))
        self$`generalInformation` <- generalInformationObject
      }
      if (!is.null(DataModelObject$`scope`)) {
        scopeObject <- GenericModelScope$new()
        scopeObject$fromJSON(jsonlite::toJSON(DataModelObject$scope, auto_unbox = TRUE))
        self$`scope` <- scopeObject
      }
      if (!is.null(DataModelObject$`dataBackground`)) {
        dataBackgroundObject <- GenericModelDataBackground$new()
        dataBackgroundObject$fromJSON(jsonlite::toJSON(DataModelObject$dataBackground, auto_unbox = TRUE))
        self$`dataBackground` <- dataBackgroundObject
      }
      if (!is.null(DataModelObject$`modelMath`)) {
        modelMathObject <- DataModelModelMath$new()
        modelMathObject$fromJSON(jsonlite::toJSON(DataModelObject$modelMath, auto_unbox = TRUE))
        self$`modelMath` <- modelMathObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "modelType": %s,
           "generalInformation": %s,
           "scope": %s,
           "dataBackground": %s,
           "modelMath": %s
        }',
        self$`modelType`,
        self$`generalInformation`$toJSON(),
        self$`scope`$toJSON(),
        self$`dataBackground`$toJSON(),
        self$`modelMath`$toJSON()
      )
    },
    fromJSONString = function(DataModelJson) {
      DataModelObject <- jsonlite::fromJSON(DataModelJson)
      self$`modelType` <- DataModelObject$`modelType`
      DataModelGeneralInformationObject <- DataModelGeneralInformation$new()
      self$`generalInformation` <- DataModelGeneralInformationObject$fromJSON(jsonlite::toJSON(DataModelObject$generalInformation, auto_unbox = TRUE))
      GenericModelScopeObject <- GenericModelScope$new()
      self$`scope` <- GenericModelScopeObject$fromJSON(jsonlite::toJSON(DataModelObject$scope, auto_unbox = TRUE))
      GenericModelDataBackgroundObject <- GenericModelDataBackground$new()
      self$`dataBackground` <- GenericModelDataBackgroundObject$fromJSON(jsonlite::toJSON(DataModelObject$dataBackground, auto_unbox = TRUE))
      DataModelModelMathObject <- DataModelModelMath$new()
      self$`modelMath` <- DataModelModelMathObject$fromJSON(jsonlite::toJSON(DataModelObject$modelMath, auto_unbox = TRUE))
    }
  )
)
