# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' DataModelModelMath Class
#'
#' @field parameter 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DataModelModelMath <- R6::R6Class(
  'DataModelModelMath',
  public = list(
    `parameter` = NULL,
    initialize = function(`parameter`){
      if (!missing(`parameter`)) {
        stopifnot(is.list(`parameter`), length(`parameter`) != 0)
        lapply(`parameter`, function(x) stopifnot(R6::is.R6(x)))
        self$`parameter` <- `parameter`
      }
    },
    toJSON = function() {
      DataModelModelMathObject <- list()
      if (!is.null(self$`parameter`)) {
        DataModelModelMathObject[['parameter']] <- lapply(self$`parameter`, function(x) x$toJSON())
      }

      DataModelModelMathObject
    },
    fromJSON = function(DataModelModelMathJson) {
      DataModelModelMathObject <- jsonlite::fromJSON(DataModelModelMathJson)
      if (!is.null(DataModelModelMathObject$`parameter`)) {
        self$`parameter` <- lapply(DataModelModelMathObject$`parameter`, function(x) {
          parameterObject <- Parameter$new()
          parameterObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          parameterObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "parameter": [%s]
        }',
        lapply(self$`parameter`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(DataModelModelMathJson) {
      DataModelModelMathObject <- jsonlite::fromJSON(DataModelModelMathJson)
      self$`parameter` <- lapply(DataModelModelMathObject$`parameter`, function(x) Parameter$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
