# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' DietaryAssessmentMethod Class
#'
#' @field collectionTool 
#' @field numberOfNonConsecutiveOneDay 
#' @field softwareTool 
#' @field numberOfFoodItems 
#' @field recordTypes 
#' @field foodDescriptors 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DietaryAssessmentMethod <- R6::R6Class(
  'DietaryAssessmentMethod',
  public = list(
    `collectionTool` = NULL,
    `numberOfNonConsecutiveOneDay` = NULL,
    `softwareTool` = NULL,
    `numberOfFoodItems` = NULL,
    `recordTypes` = NULL,
    `foodDescriptors` = NULL,
    initialize = function(`collectionTool`, `numberOfNonConsecutiveOneDay`, `softwareTool`, `numberOfFoodItems`, `recordTypes`, `foodDescriptors`){
      if (!missing(`collectionTool`)) {
        stopifnot(is.character(`collectionTool`), length(`collectionTool`) == 1)
        self$`collectionTool` <- `collectionTool`
      }
      if (!missing(`numberOfNonConsecutiveOneDay`)) {
        stopifnot(is.character(`numberOfNonConsecutiveOneDay`), length(`numberOfNonConsecutiveOneDay`) == 1)
        self$`numberOfNonConsecutiveOneDay` <- `numberOfNonConsecutiveOneDay`
      }
      if (!missing(`softwareTool`)) {
        stopifnot(is.character(`softwareTool`), length(`softwareTool`) == 1)
        self$`softwareTool` <- `softwareTool`
      }
      if (!missing(`numberOfFoodItems`)) {
        stopifnot(is.list(`numberOfFoodItems`), length(`numberOfFoodItems`) != 0)
        lapply(`numberOfFoodItems`, function(x) stopifnot(is.character(x)))
        self$`numberOfFoodItems` <- `numberOfFoodItems`
      }
      if (!missing(`recordTypes`)) {
        stopifnot(is.list(`recordTypes`), length(`recordTypes`) != 0)
        lapply(`recordTypes`, function(x) stopifnot(is.character(x)))
        self$`recordTypes` <- `recordTypes`
      }
      if (!missing(`foodDescriptors`)) {
        stopifnot(is.list(`foodDescriptors`), length(`foodDescriptors`) != 0)
        lapply(`foodDescriptors`, function(x) stopifnot(is.character(x)))
        self$`foodDescriptors` <- `foodDescriptors`
      }
    },
    toJSON = function() {
      DietaryAssessmentMethodObject <- list()
      if (!is.null(self$`collectionTool`)) {
        DietaryAssessmentMethodObject[['collectionTool']] <- self$`collectionTool`
      }
      if (!is.null(self$`numberOfNonConsecutiveOneDay`)) {
        DietaryAssessmentMethodObject[['numberOfNonConsecutiveOneDay']] <- self$`numberOfNonConsecutiveOneDay`
      }
      if (!is.null(self$`softwareTool`)) {
        DietaryAssessmentMethodObject[['softwareTool']] <- self$`softwareTool`
      }
      if (!is.null(self$`numberOfFoodItems`)) {
        DietaryAssessmentMethodObject[['numberOfFoodItems']] <- self$`numberOfFoodItems`
      }
      if (!is.null(self$`recordTypes`)) {
        DietaryAssessmentMethodObject[['recordTypes']] <- self$`recordTypes`
      }
      if (!is.null(self$`foodDescriptors`)) {
        DietaryAssessmentMethodObject[['foodDescriptors']] <- self$`foodDescriptors`
      }

      DietaryAssessmentMethodObject
    },
    fromJSON = function(DietaryAssessmentMethodJson) {
      DietaryAssessmentMethodObject <- jsonlite::fromJSON(DietaryAssessmentMethodJson)
      if (!is.null(DietaryAssessmentMethodObject$`collectionTool`)) {
        self$`collectionTool` <- DietaryAssessmentMethodObject$`collectionTool`
      }
      if (!is.null(DietaryAssessmentMethodObject$`numberOfNonConsecutiveOneDay`)) {
        self$`numberOfNonConsecutiveOneDay` <- DietaryAssessmentMethodObject$`numberOfNonConsecutiveOneDay`
      }
      if (!is.null(DietaryAssessmentMethodObject$`softwareTool`)) {
        self$`softwareTool` <- DietaryAssessmentMethodObject$`softwareTool`
      }
      if (!is.null(DietaryAssessmentMethodObject$`numberOfFoodItems`)) {
        self$`numberOfFoodItems` <- DietaryAssessmentMethodObject$`numberOfFoodItems`
      }
      if (!is.null(DietaryAssessmentMethodObject$`recordTypes`)) {
        self$`recordTypes` <- DietaryAssessmentMethodObject$`recordTypes`
      }
      if (!is.null(DietaryAssessmentMethodObject$`foodDescriptors`)) {
        self$`foodDescriptors` <- DietaryAssessmentMethodObject$`foodDescriptors`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "collectionTool": %s,
           "numberOfNonConsecutiveOneDay": %s,
           "softwareTool": %s,
           "numberOfFoodItems": [%s],
           "recordTypes": [%s],
           "foodDescriptors": [%s]
        }',
        self$`collectionTool`,
        self$`numberOfNonConsecutiveOneDay`,
        self$`softwareTool`,
        lapply(self$`numberOfFoodItems`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`recordTypes`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`foodDescriptors`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(DietaryAssessmentMethodJson) {
      DietaryAssessmentMethodObject <- jsonlite::fromJSON(DietaryAssessmentMethodJson)
      self$`collectionTool` <- DietaryAssessmentMethodObject$`collectionTool`
      self$`numberOfNonConsecutiveOneDay` <- DietaryAssessmentMethodObject$`numberOfNonConsecutiveOneDay`
      self$`softwareTool` <- DietaryAssessmentMethodObject$`softwareTool`
      self$`numberOfFoodItems` <- DietaryAssessmentMethodObject$`numberOfFoodItems`
      self$`recordTypes` <- DietaryAssessmentMethodObject$`recordTypes`
      self$`foodDescriptors` <- DietaryAssessmentMethodObject$`foodDescriptors`
    }
  )
)
