# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' DoseResponseModelModelMath Class
#'
#' @field parameter 
#' @field qualityMeasures 
#' @field modelEquation 
#' @field fittingProcedure 
#' @field exposure 
#' @field event 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DoseResponseModelModelMath <- R6::R6Class(
  'DoseResponseModelModelMath',
  public = list(
    `parameter` = NULL,
    `qualityMeasures` = NULL,
    `modelEquation` = NULL,
    `fittingProcedure` = NULL,
    `exposure` = NULL,
    `event` = NULL,
    initialize = function(`parameter`, `qualityMeasures`, `modelEquation`, `fittingProcedure`, `exposure`, `event`){
      if (!missing(`parameter`)) {
        stopifnot(is.list(`parameter`), length(`parameter`) != 0)
        lapply(`parameter`, function(x) stopifnot(R6::is.R6(x)))
        self$`parameter` <- `parameter`
      }
      if (!missing(`qualityMeasures`)) {
        stopifnot(is.list(`qualityMeasures`), length(`qualityMeasures`) != 0)
        lapply(`qualityMeasures`, function(x) stopifnot(R6::is.R6(x)))
        self$`qualityMeasures` <- `qualityMeasures`
      }
      if (!missing(`modelEquation`)) {
        stopifnot(is.list(`modelEquation`), length(`modelEquation`) != 0)
        lapply(`modelEquation`, function(x) stopifnot(R6::is.R6(x)))
        self$`modelEquation` <- `modelEquation`
      }
      if (!missing(`fittingProcedure`)) {
        stopifnot(is.character(`fittingProcedure`), length(`fittingProcedure`) == 1)
        self$`fittingProcedure` <- `fittingProcedure`
      }
      if (!missing(`exposure`)) {
        stopifnot(R6::is.R6(`exposure`))
        self$`exposure` <- `exposure`
      }
      if (!missing(`event`)) {
        stopifnot(is.list(`event`), length(`event`) != 0)
        lapply(`event`, function(x) stopifnot(is.character(x)))
        self$`event` <- `event`
      }
    },
    toJSON = function() {
      DoseResponseModelModelMathObject <- list()
      if (!is.null(self$`parameter`)) {
        DoseResponseModelModelMathObject[['parameter']] <- lapply(self$`parameter`, function(x) x$toJSON())
      }
      if (!is.null(self$`qualityMeasures`)) {
        DoseResponseModelModelMathObject[['qualityMeasures']] <- lapply(self$`qualityMeasures`, function(x) x$toJSON())
      }
      if (!is.null(self$`modelEquation`)) {
        DoseResponseModelModelMathObject[['modelEquation']] <- lapply(self$`modelEquation`, function(x) x$toJSON())
      }
      if (!is.null(self$`fittingProcedure`)) {
        DoseResponseModelModelMathObject[['fittingProcedure']] <- self$`fittingProcedure`
      }
      if (!is.null(self$`exposure`)) {
        DoseResponseModelModelMathObject[['exposure']] <- self$`exposure`$toJSON()
      }
      if (!is.null(self$`event`)) {
        DoseResponseModelModelMathObject[['event']] <- self$`event`
      }

      DoseResponseModelModelMathObject
    },
    fromJSON = function(DoseResponseModelModelMathJson) {
      DoseResponseModelModelMathObject <- jsonlite::fromJSON(DoseResponseModelModelMathJson)
      if (!is.null(DoseResponseModelModelMathObject$`parameter`)) {
        self$`parameter` <- lapply(DoseResponseModelModelMathObject$`parameter`, function(x) {
          parameterObject <- Parameter$new()
          parameterObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          parameterObject
        })
      }
      if (!is.null(DoseResponseModelModelMathObject$`qualityMeasures`)) {
        self$`qualityMeasures` <- lapply(DoseResponseModelModelMathObject$`qualityMeasures`, function(x) {
          qualityMeasuresObject <- QualityMeasures$new()
          qualityMeasuresObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          qualityMeasuresObject
        })
      }
      if (!is.null(DoseResponseModelModelMathObject$`modelEquation`)) {
        self$`modelEquation` <- lapply(DoseResponseModelModelMathObject$`modelEquation`, function(x) {
          modelEquationObject <- ModelEquation$new()
          modelEquationObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          modelEquationObject
        })
      }
      if (!is.null(DoseResponseModelModelMathObject$`fittingProcedure`)) {
        self$`fittingProcedure` <- DoseResponseModelModelMathObject$`fittingProcedure`
      }
      if (!is.null(DoseResponseModelModelMathObject$`exposure`)) {
        exposureObject <- Exposure$new()
        exposureObject$fromJSON(jsonlite::toJSON(DoseResponseModelModelMathObject$exposure, auto_unbox = TRUE))
        self$`exposure` <- exposureObject
      }
      if (!is.null(DoseResponseModelModelMathObject$`event`)) {
        self$`event` <- DoseResponseModelModelMathObject$`event`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "parameter": [%s],
           "qualityMeasures": [%s],
           "modelEquation": [%s],
           "fittingProcedure": %s,
           "exposure": %s,
           "event": [%s]
        }',
        lapply(self$`parameter`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`qualityMeasures`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`modelEquation`, function(x) paste(x$toJSON(), sep=",")),
        self$`fittingProcedure`,
        self$`exposure`$toJSON(),
        lapply(self$`event`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(DoseResponseModelModelMathJson) {
      DoseResponseModelModelMathObject <- jsonlite::fromJSON(DoseResponseModelModelMathJson)
      self$`parameter` <- lapply(DoseResponseModelModelMathObject$`parameter`, function(x) Parameter$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`qualityMeasures` <- lapply(DoseResponseModelModelMathObject$`qualityMeasures`, function(x) QualityMeasures$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`modelEquation` <- lapply(DoseResponseModelModelMathObject$`modelEquation`, function(x) ModelEquation$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`fittingProcedure` <- DoseResponseModelModelMathObject$`fittingProcedure`
      ExposureObject <- Exposure$new()
      self$`exposure` <- ExposureObject$fromJSON(jsonlite::toJSON(DoseResponseModelModelMathObject$exposure, auto_unbox = TRUE))
      self$`event` <- DoseResponseModelModelMathObject$`event`
    }
  )
)
