# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' DoseResponseModelGeneralInformation Class
#'
#' @field modelName 
#' @field source 
#' @field identifier 
#' @field author 
#' @field creator 
#' @field creationDate 
#' @field modificationDate 
#' @field rights 
#' @field availability 
#' @field url 
#' @field format 
#' @field reference 
#' @field language 
#' @field software 
#' @field languageWrittenIn 
#' @field modelCategory 
#' @field status 
#' @field objective 
#' @field description 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
DoseResponseModelGeneralInformation <- R6::R6Class(
  'DoseResponseModelGeneralInformation',
  public = list(
    `modelName` = NULL,
    `source` = NULL,
    `identifier` = NULL,
    `author` = NULL,
    `creator` = NULL,
    `creationDate` = NULL,
    `modificationDate` = NULL,
    `rights` = NULL,
    `availability` = NULL,
    `url` = NULL,
    `format` = NULL,
    `reference` = NULL,
    `language` = NULL,
    `software` = NULL,
    `languageWrittenIn` = NULL,
    `modelCategory` = NULL,
    `status` = NULL,
    `objective` = NULL,
    `description` = NULL,
    initialize = function(`modelName`, `source`, `identifier`, `author`, `creator`, `creationDate`, `modificationDate`, `rights`, `availability`, `url`, `format`, `reference`, `language`, `software`, `languageWrittenIn`, `modelCategory`, `status`, `objective`, `description`){
      if (!missing(`modelName`)) {
        stopifnot(is.character(`modelName`), length(`modelName`) == 1)
        self$`modelName` <- `modelName`
      }
      if (!missing(`source`)) {
        stopifnot(is.character(`source`), length(`source`) == 1)
        self$`source` <- `source`
      }
      if (!missing(`identifier`)) {
        stopifnot(is.character(`identifier`), length(`identifier`) == 1)
        self$`identifier` <- `identifier`
      }
      if (!missing(`author`)) {
        stopifnot(is.list(`author`), length(`author`) != 0)
        lapply(`author`, function(x) stopifnot(R6::is.R6(x)))
        self$`author` <- `author`
      }
      if (!missing(`creator`)) {
        stopifnot(is.list(`creator`), length(`creator`) != 0)
        lapply(`creator`, function(x) stopifnot(R6::is.R6(x)))
        self$`creator` <- `creator`
      }
      if (!missing(`creationDate`)) {
        stopifnot(is.character(`creationDate`), length(`creationDate`) == 1)
        self$`creationDate` <- `creationDate`
      }
      if (!missing(`modificationDate`)) {
        stopifnot(is.list(`modificationDate`), length(`modificationDate`) != 0)
        lapply(`modificationDate`, function(x) stopifnot(is.character(x)))
        self$`modificationDate` <- `modificationDate`
      }
      if (!missing(`rights`)) {
        stopifnot(is.character(`rights`), length(`rights`) == 1)
        self$`rights` <- `rights`
      }
      if (!missing(`availability`)) {
        stopifnot(is.character(`availability`), length(`availability`) == 1)
        self$`availability` <- `availability`
      }
      if (!missing(`url`)) {
        stopifnot(is.character(`url`), length(`url`) == 1)
        self$`url` <- `url`
      }
      if (!missing(`format`)) {
        stopifnot(is.character(`format`), length(`format`) == 1)
        self$`format` <- `format`
      }
      if (!missing(`reference`)) {
        stopifnot(is.list(`reference`), length(`reference`) != 0)
        lapply(`reference`, function(x) stopifnot(R6::is.R6(x)))
        self$`reference` <- `reference`
      }
      if (!missing(`language`)) {
        stopifnot(is.character(`language`), length(`language`) == 1)
        self$`language` <- `language`
      }
      if (!missing(`software`)) {
        stopifnot(is.character(`software`), length(`software`) == 1)
        self$`software` <- `software`
      }
      if (!missing(`languageWrittenIn`)) {
        stopifnot(is.character(`languageWrittenIn`), length(`languageWrittenIn`) == 1)
        self$`languageWrittenIn` <- `languageWrittenIn`
      }
      if (!missing(`modelCategory`)) {
        stopifnot(R6::is.R6(`modelCategory`))
        self$`modelCategory` <- `modelCategory`
      }
      if (!missing(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
      if (!missing(`objective`)) {
        stopifnot(is.character(`objective`), length(`objective`) == 1)
        self$`objective` <- `objective`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
    },
    toJSON = function() {
      DoseResponseModelGeneralInformationObject <- list()
      if (!is.null(self$`modelName`)) {
        DoseResponseModelGeneralInformationObject[['modelName']] <- self$`modelName`
      }
      if (!is.null(self$`source`)) {
        DoseResponseModelGeneralInformationObject[['source']] <- self$`source`
      }
      if (!is.null(self$`identifier`)) {
        DoseResponseModelGeneralInformationObject[['identifier']] <- self$`identifier`
      }
      if (!is.null(self$`author`)) {
        DoseResponseModelGeneralInformationObject[['author']] <- lapply(self$`author`, function(x) x$toJSON())
      }
      if (!is.null(self$`creator`)) {
        DoseResponseModelGeneralInformationObject[['creator']] <- lapply(self$`creator`, function(x) x$toJSON())
      }
      if (!is.null(self$`creationDate`)) {
        DoseResponseModelGeneralInformationObject[['creationDate']] <- self$`creationDate`
      }
      if (!is.null(self$`modificationDate`)) {
        DoseResponseModelGeneralInformationObject[['modificationDate']] <- self$`modificationDate`
      }
      if (!is.null(self$`rights`)) {
        DoseResponseModelGeneralInformationObject[['rights']] <- self$`rights`
      }
      if (!is.null(self$`availability`)) {
        DoseResponseModelGeneralInformationObject[['availability']] <- self$`availability`
      }
      if (!is.null(self$`url`)) {
        DoseResponseModelGeneralInformationObject[['url']] <- self$`url`
      }
      if (!is.null(self$`format`)) {
        DoseResponseModelGeneralInformationObject[['format']] <- self$`format`
      }
      if (!is.null(self$`reference`)) {
        DoseResponseModelGeneralInformationObject[['reference']] <- lapply(self$`reference`, function(x) x$toJSON())
      }
      if (!is.null(self$`language`)) {
        DoseResponseModelGeneralInformationObject[['language']] <- self$`language`
      }
      if (!is.null(self$`software`)) {
        DoseResponseModelGeneralInformationObject[['software']] <- self$`software`
      }
      if (!is.null(self$`languageWrittenIn`)) {
        DoseResponseModelGeneralInformationObject[['languageWrittenIn']] <- self$`languageWrittenIn`
      }
      if (!is.null(self$`modelCategory`)) {
        DoseResponseModelGeneralInformationObject[['modelCategory']] <- self$`modelCategory`$toJSON()
      }
      if (!is.null(self$`status`)) {
        DoseResponseModelGeneralInformationObject[['status']] <- self$`status`
      }
      if (!is.null(self$`objective`)) {
        DoseResponseModelGeneralInformationObject[['objective']] <- self$`objective`
      }
      if (!is.null(self$`description`)) {
        DoseResponseModelGeneralInformationObject[['description']] <- self$`description`
      }

      DoseResponseModelGeneralInformationObject
    },
    fromJSON = function(DoseResponseModelGeneralInformationJson) {
      DoseResponseModelGeneralInformationObject <- jsonlite::fromJSON(DoseResponseModelGeneralInformationJson)
      if (!is.null(DoseResponseModelGeneralInformationObject$`modelName`)) {
        self$`modelName` <- DoseResponseModelGeneralInformationObject$`modelName`
      }
      if (!is.null(DoseResponseModelGeneralInformationObject$`source`)) {
        self$`source` <- DoseResponseModelGeneralInformationObject$`source`
      }
      if (!is.null(DoseResponseModelGeneralInformationObject$`identifier`)) {
        self$`identifier` <- DoseResponseModelGeneralInformationObject$`identifier`
      }
      if (!is.null(DoseResponseModelGeneralInformationObject$`author`)) {
        self$`author` <- lapply(DoseResponseModelGeneralInformationObject$`author`, function(x) {
          authorObject <- Contact$new()
          authorObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          authorObject
        })
      }
      if (!is.null(DoseResponseModelGeneralInformationObject$`creator`)) {
        self$`creator` <- lapply(DoseResponseModelGeneralInformationObject$`creator`, function(x) {
          creatorObject <- Contact$new()
          creatorObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          creatorObject
        })
      }
      if (!is.null(DoseResponseModelGeneralInformationObject$`creationDate`)) {
        self$`creationDate` <- DoseResponseModelGeneralInformationObject$`creationDate`
      }
      if (!is.null(DoseResponseModelGeneralInformationObject$`modificationDate`)) {
        self$`modificationDate` <- DoseResponseModelGeneralInformationObject$`modificationDate`
      }
      if (!is.null(DoseResponseModelGeneralInformationObject$`rights`)) {
        self$`rights` <- DoseResponseModelGeneralInformationObject$`rights`
      }
      if (!is.null(DoseResponseModelGeneralInformationObject$`availability`)) {
        self$`availability` <- DoseResponseModelGeneralInformationObject$`availability`
      }
      if (!is.null(DoseResponseModelGeneralInformationObject$`url`)) {
        self$`url` <- DoseResponseModelGeneralInformationObject$`url`
      }
      if (!is.null(DoseResponseModelGeneralInformationObject$`format`)) {
        self$`format` <- DoseResponseModelGeneralInformationObject$`format`
      }
      if (!is.null(DoseResponseModelGeneralInformationObject$`reference`)) {
        self$`reference` <- lapply(DoseResponseModelGeneralInformationObject$`reference`, function(x) {
          referenceObject <- Reference$new()
          referenceObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          referenceObject
        })
      }
      if (!is.null(DoseResponseModelGeneralInformationObject$`language`)) {
        self$`language` <- DoseResponseModelGeneralInformationObject$`language`
      }
      if (!is.null(DoseResponseModelGeneralInformationObject$`software`)) {
        self$`software` <- DoseResponseModelGeneralInformationObject$`software`
      }
      if (!is.null(DoseResponseModelGeneralInformationObject$`languageWrittenIn`)) {
        self$`languageWrittenIn` <- DoseResponseModelGeneralInformationObject$`languageWrittenIn`
      }
      if (!is.null(DoseResponseModelGeneralInformationObject$`modelCategory`)) {
        modelCategoryObject <- ModelCategory$new()
        modelCategoryObject$fromJSON(jsonlite::toJSON(DoseResponseModelGeneralInformationObject$modelCategory, auto_unbox = TRUE))
        self$`modelCategory` <- modelCategoryObject
      }
      if (!is.null(DoseResponseModelGeneralInformationObject$`status`)) {
        self$`status` <- DoseResponseModelGeneralInformationObject$`status`
      }
      if (!is.null(DoseResponseModelGeneralInformationObject$`objective`)) {
        self$`objective` <- DoseResponseModelGeneralInformationObject$`objective`
      }
      if (!is.null(DoseResponseModelGeneralInformationObject$`description`)) {
        self$`description` <- DoseResponseModelGeneralInformationObject$`description`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "modelName": %s,
           "source": %s,
           "identifier": %s,
           "author": [%s],
           "creator": [%s],
           "creationDate": %s,
           "modificationDate": [%s],
           "rights": %s,
           "availability": %s,
           "url": %s,
           "format": %s,
           "reference": [%s],
           "language": %s,
           "software": %s,
           "languageWrittenIn": %s,
           "modelCategory": %s,
           "status": %s,
           "objective": %s,
           "description": %s
        }',
        self$`modelName`,
        self$`source`,
        self$`identifier`,
        lapply(self$`author`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`creator`, function(x) paste(x$toJSON(), sep=",")),
        self$`creationDate`,
        lapply(self$`modificationDate`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`rights`,
        self$`availability`,
        self$`url`,
        self$`format`,
        lapply(self$`reference`, function(x) paste(x$toJSON(), sep=",")),
        self$`language`,
        self$`software`,
        self$`languageWrittenIn`,
        self$`modelCategory`$toJSON(),
        self$`status`,
        self$`objective`,
        self$`description`
      )
    },
    fromJSONString = function(DoseResponseModelGeneralInformationJson) {
      DoseResponseModelGeneralInformationObject <- jsonlite::fromJSON(DoseResponseModelGeneralInformationJson)
      self$`modelName` <- DoseResponseModelGeneralInformationObject$`modelName`
      self$`source` <- DoseResponseModelGeneralInformationObject$`source`
      self$`identifier` <- DoseResponseModelGeneralInformationObject$`identifier`
      self$`author` <- lapply(DoseResponseModelGeneralInformationObject$`author`, function(x) Contact$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`creator` <- lapply(DoseResponseModelGeneralInformationObject$`creator`, function(x) Contact$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`creationDate` <- DoseResponseModelGeneralInformationObject$`creationDate`
      self$`modificationDate` <- DoseResponseModelGeneralInformationObject$`modificationDate`
      self$`rights` <- DoseResponseModelGeneralInformationObject$`rights`
      self$`availability` <- DoseResponseModelGeneralInformationObject$`availability`
      self$`url` <- DoseResponseModelGeneralInformationObject$`url`
      self$`format` <- DoseResponseModelGeneralInformationObject$`format`
      self$`reference` <- lapply(DoseResponseModelGeneralInformationObject$`reference`, function(x) Reference$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`language` <- DoseResponseModelGeneralInformationObject$`language`
      self$`software` <- DoseResponseModelGeneralInformationObject$`software`
      self$`languageWrittenIn` <- DoseResponseModelGeneralInformationObject$`languageWrittenIn`
      ModelCategoryObject <- ModelCategory$new()
      self$`modelCategory` <- ModelCategoryObject$fromJSON(jsonlite::toJSON(DoseResponseModelGeneralInformationObject$modelCategory, auto_unbox = TRUE))
      self$`status` <- DoseResponseModelGeneralInformationObject$`status`
      self$`objective` <- DoseResponseModelGeneralInformationObject$`objective`
      self$`description` <- DoseResponseModelGeneralInformationObject$`description`
    }
  )
)
