# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Exposure Class
#'
#' @field treatment 
#' @field contamination 
#' @field type 
#' @field scenario 
#' @field uncertaintyEstimation 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Exposure <- R6::R6Class(
  'Exposure',
  public = list(
    `treatment` = NULL,
    `contamination` = NULL,
    `type` = NULL,
    `scenario` = NULL,
    `uncertaintyEstimation` = NULL,
    initialize = function(`treatment`, `contamination`, `type`, `scenario`, `uncertaintyEstimation`){
      if (!missing(`treatment`)) {
        stopifnot(is.list(`treatment`), length(`treatment`) != 0)
        lapply(`treatment`, function(x) stopifnot(is.character(x)))
        self$`treatment` <- `treatment`
      }
      if (!missing(`contamination`)) {
        stopifnot(is.list(`contamination`), length(`contamination`) != 0)
        lapply(`contamination`, function(x) stopifnot(is.character(x)))
        self$`contamination` <- `contamination`
      }
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`scenario`)) {
        stopifnot(is.list(`scenario`), length(`scenario`) != 0)
        lapply(`scenario`, function(x) stopifnot(is.character(x)))
        self$`scenario` <- `scenario`
      }
      if (!missing(`uncertaintyEstimation`)) {
        stopifnot(is.character(`uncertaintyEstimation`), length(`uncertaintyEstimation`) == 1)
        self$`uncertaintyEstimation` <- `uncertaintyEstimation`
      }
    },
    toJSON = function() {
      ExposureObject <- list()
      if (!is.null(self$`treatment`)) {
        ExposureObject[['treatment']] <- self$`treatment`
      }
      if (!is.null(self$`contamination`)) {
        ExposureObject[['contamination']] <- self$`contamination`
      }
      if (!is.null(self$`type`)) {
        ExposureObject[['type']] <- self$`type`
      }
      if (!is.null(self$`scenario`)) {
        ExposureObject[['scenario']] <- self$`scenario`
      }
      if (!is.null(self$`uncertaintyEstimation`)) {
        ExposureObject[['uncertaintyEstimation']] <- self$`uncertaintyEstimation`
      }

      ExposureObject
    },
    fromJSON = function(ExposureJson) {
      ExposureObject <- jsonlite::fromJSON(ExposureJson)
      if (!is.null(ExposureObject$`treatment`)) {
        self$`treatment` <- ExposureObject$`treatment`
      }
      if (!is.null(ExposureObject$`contamination`)) {
        self$`contamination` <- ExposureObject$`contamination`
      }
      if (!is.null(ExposureObject$`type`)) {
        self$`type` <- ExposureObject$`type`
      }
      if (!is.null(ExposureObject$`scenario`)) {
        self$`scenario` <- ExposureObject$`scenario`
      }
      if (!is.null(ExposureObject$`uncertaintyEstimation`)) {
        self$`uncertaintyEstimation` <- ExposureObject$`uncertaintyEstimation`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "treatment": [%s],
           "contamination": [%s],
           "type": %s,
           "scenario": [%s],
           "uncertaintyEstimation": %s
        }',
        lapply(self$`treatment`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`contamination`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`type`,
        lapply(self$`scenario`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`uncertaintyEstimation`
      )
    },
    fromJSONString = function(ExposureJson) {
      ExposureObject <- jsonlite::fromJSON(ExposureJson)
      self$`treatment` <- ExposureObject$`treatment`
      self$`contamination` <- ExposureObject$`contamination`
      self$`type` <- ExposureObject$`type`
      self$`scenario` <- ExposureObject$`scenario`
      self$`uncertaintyEstimation` <- ExposureObject$`uncertaintyEstimation`
    }
  )
)
