# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' GenericModelDataBackground Class
#'
#' @field study 
#' @field studySample 
#' @field dietaryAssessmentMethod 
#' @field laboratory 
#' @field assay 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GenericModelDataBackground <- R6::R6Class(
  'GenericModelDataBackground',
  public = list(
    `study` = NULL,
    `studySample` = NULL,
    `dietaryAssessmentMethod` = NULL,
    `laboratory` = NULL,
    `assay` = NULL,
    initialize = function(`study`, `studySample`, `dietaryAssessmentMethod`, `laboratory`, `assay`){
      if (!missing(`study`)) {
        stopifnot(R6::is.R6(`study`))
        self$`study` <- `study`
      }
      if (!missing(`studySample`)) {
        stopifnot(is.list(`studySample`), length(`studySample`) != 0)
        lapply(`studySample`, function(x) stopifnot(R6::is.R6(x)))
        self$`studySample` <- `studySample`
      }
      if (!missing(`dietaryAssessmentMethod`)) {
        stopifnot(is.list(`dietaryAssessmentMethod`), length(`dietaryAssessmentMethod`) != 0)
        lapply(`dietaryAssessmentMethod`, function(x) stopifnot(R6::is.R6(x)))
        self$`dietaryAssessmentMethod` <- `dietaryAssessmentMethod`
      }
      if (!missing(`laboratory`)) {
        stopifnot(is.list(`laboratory`), length(`laboratory`) != 0)
        lapply(`laboratory`, function(x) stopifnot(R6::is.R6(x)))
        self$`laboratory` <- `laboratory`
      }
      if (!missing(`assay`)) {
        stopifnot(is.list(`assay`), length(`assay`) != 0)
        lapply(`assay`, function(x) stopifnot(R6::is.R6(x)))
        self$`assay` <- `assay`
      }
    },
    toJSON = function() {
      GenericModelDataBackgroundObject <- list()
      if (!is.null(self$`study`)) {
        GenericModelDataBackgroundObject[['study']] <- self$`study`$toJSON()
      }
      if (!is.null(self$`studySample`)) {
        GenericModelDataBackgroundObject[['studySample']] <- lapply(self$`studySample`, function(x) x$toJSON())
      }
      if (!is.null(self$`dietaryAssessmentMethod`)) {
        GenericModelDataBackgroundObject[['dietaryAssessmentMethod']] <- lapply(self$`dietaryAssessmentMethod`, function(x) x$toJSON())
      }
      if (!is.null(self$`laboratory`)) {
        GenericModelDataBackgroundObject[['laboratory']] <- lapply(self$`laboratory`, function(x) x$toJSON())
      }
      if (!is.null(self$`assay`)) {
        GenericModelDataBackgroundObject[['assay']] <- lapply(self$`assay`, function(x) x$toJSON())
      }

      GenericModelDataBackgroundObject
    },
    fromJSON = function(GenericModelDataBackgroundJson) {
      GenericModelDataBackgroundObject <- jsonlite::fromJSON(GenericModelDataBackgroundJson)
      if (!is.null(GenericModelDataBackgroundObject$`study`)) {
        studyObject <- Study$new()
        studyObject$fromJSON(jsonlite::toJSON(GenericModelDataBackgroundObject$study, auto_unbox = TRUE))
        self$`study` <- studyObject
      }
      if (!is.null(GenericModelDataBackgroundObject$`studySample`)) {
        self$`studySample` <- lapply(GenericModelDataBackgroundObject$`studySample`, function(x) {
          studySampleObject <- StudySample$new()
          studySampleObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          studySampleObject
        })
      }
      if (!is.null(GenericModelDataBackgroundObject$`dietaryAssessmentMethod`)) {
        self$`dietaryAssessmentMethod` <- lapply(GenericModelDataBackgroundObject$`dietaryAssessmentMethod`, function(x) {
          dietaryAssessmentMethodObject <- DietaryAssessmentMethod$new()
          dietaryAssessmentMethodObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          dietaryAssessmentMethodObject
        })
      }
      if (!is.null(GenericModelDataBackgroundObject$`laboratory`)) {
        self$`laboratory` <- lapply(GenericModelDataBackgroundObject$`laboratory`, function(x) {
          laboratoryObject <- Laboratory$new()
          laboratoryObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          laboratoryObject
        })
      }
      if (!is.null(GenericModelDataBackgroundObject$`assay`)) {
        self$`assay` <- lapply(GenericModelDataBackgroundObject$`assay`, function(x) {
          assayObject <- Assay$new()
          assayObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          assayObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "study": %s,
           "studySample": [%s],
           "dietaryAssessmentMethod": [%s],
           "laboratory": [%s],
           "assay": [%s]
        }',
        self$`study`$toJSON(),
        lapply(self$`studySample`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`dietaryAssessmentMethod`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`laboratory`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`assay`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(GenericModelDataBackgroundJson) {
      GenericModelDataBackgroundObject <- jsonlite::fromJSON(GenericModelDataBackgroundJson)
      StudyObject <- Study$new()
      self$`study` <- StudyObject$fromJSON(jsonlite::toJSON(GenericModelDataBackgroundObject$study, auto_unbox = TRUE))
      self$`studySample` <- lapply(GenericModelDataBackgroundObject$`studySample`, function(x) StudySample$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`dietaryAssessmentMethod` <- lapply(GenericModelDataBackgroundObject$`dietaryAssessmentMethod`, function(x) DietaryAssessmentMethod$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`laboratory` <- lapply(GenericModelDataBackgroundObject$`laboratory`, function(x) Laboratory$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`assay` <- lapply(GenericModelDataBackgroundObject$`assay`, function(x) Assay$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
