# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' GenericModel Class
#'
#' @field modelType 
#' @field generalInformation 
#' @field scope 
#' @field dataBackground 
#' @field modelMath 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
GenericModel <- R6::R6Class(
  'GenericModel',
  public = list(
    `modelType` = NULL,
    `generalInformation` = NULL,
    `scope` = NULL,
    `dataBackground` = NULL,
    `modelMath` = NULL,
    initialize = function(`modelType`, `generalInformation`, `scope`, `dataBackground`, `modelMath`){
      if (!missing(`modelType`)) {
        stopifnot(is.character(`modelType`), length(`modelType`) == 1)
        self$`modelType` <- `modelType`
      }
      if (!missing(`generalInformation`)) {
        stopifnot(R6::is.R6(`generalInformation`))
        self$`generalInformation` <- `generalInformation`
      }
      if (!missing(`scope`)) {
        stopifnot(R6::is.R6(`scope`))
        self$`scope` <- `scope`
      }
      if (!missing(`dataBackground`)) {
        stopifnot(R6::is.R6(`dataBackground`))
        self$`dataBackground` <- `dataBackground`
      }
      if (!missing(`modelMath`)) {
        stopifnot(R6::is.R6(`modelMath`))
        self$`modelMath` <- `modelMath`
      }
    },
    toJSON = function() {
      GenericModelObject <- list()
      if (!is.null(self$`modelType`)) {
        GenericModelObject[['modelType']] <- self$`modelType`
      }
      if (!is.null(self$`generalInformation`)) {
        GenericModelObject[['generalInformation']] <- self$`generalInformation`$toJSON()
      }
      if (!is.null(self$`scope`)) {
        GenericModelObject[['scope']] <- self$`scope`$toJSON()
      }
      if (!is.null(self$`dataBackground`)) {
        GenericModelObject[['dataBackground']] <- self$`dataBackground`$toJSON()
      }
      if (!is.null(self$`modelMath`)) {
        GenericModelObject[['modelMath']] <- self$`modelMath`$toJSON()
      }

      GenericModelObject
    },
    fromJSON = function(GenericModelJson) {
      GenericModelObject <- jsonlite::fromJSON(GenericModelJson)
      if (!is.null(GenericModelObject$`modelType`)) {
        self$`modelType` <- GenericModelObject$`modelType`
      }
      if (!is.null(GenericModelObject$`generalInformation`)) {
        generalInformationObject <- GenericModelGeneralInformation$new()
        generalInformationObject$fromJSON(jsonlite::toJSON(GenericModelObject$generalInformation, auto_unbox = TRUE))
        self$`generalInformation` <- generalInformationObject
      }
      if (!is.null(GenericModelObject$`scope`)) {
        scopeObject <- GenericModelScope$new()
        scopeObject$fromJSON(jsonlite::toJSON(GenericModelObject$scope, auto_unbox = TRUE))
        self$`scope` <- scopeObject
      }
      if (!is.null(GenericModelObject$`dataBackground`)) {
        dataBackgroundObject <- GenericModelDataBackground$new()
        dataBackgroundObject$fromJSON(jsonlite::toJSON(GenericModelObject$dataBackground, auto_unbox = TRUE))
        self$`dataBackground` <- dataBackgroundObject
      }
      if (!is.null(GenericModelObject$`modelMath`)) {
        modelMathObject <- GenericModelModelMath$new()
        modelMathObject$fromJSON(jsonlite::toJSON(GenericModelObject$modelMath, auto_unbox = TRUE))
        self$`modelMath` <- modelMathObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "modelType": %s,
           "generalInformation": %s,
           "scope": %s,
           "dataBackground": %s,
           "modelMath": %s
        }',
        self$`modelType`,
        self$`generalInformation`$toJSON(),
        self$`scope`$toJSON(),
        self$`dataBackground`$toJSON(),
        self$`modelMath`$toJSON()
      )
    },
    fromJSONString = function(GenericModelJson) {
      GenericModelObject <- jsonlite::fromJSON(GenericModelJson)
      self$`modelType` <- GenericModelObject$`modelType`
      GenericModelGeneralInformationObject <- GenericModelGeneralInformation$new()
      self$`generalInformation` <- GenericModelGeneralInformationObject$fromJSON(jsonlite::toJSON(GenericModelObject$generalInformation, auto_unbox = TRUE))
      GenericModelScopeObject <- GenericModelScope$new()
      self$`scope` <- GenericModelScopeObject$fromJSON(jsonlite::toJSON(GenericModelObject$scope, auto_unbox = TRUE))
      GenericModelDataBackgroundObject <- GenericModelDataBackground$new()
      self$`dataBackground` <- GenericModelDataBackgroundObject$fromJSON(jsonlite::toJSON(GenericModelObject$dataBackground, auto_unbox = TRUE))
      GenericModelModelMathObject <- GenericModelModelMath$new()
      self$`modelMath` <- GenericModelModelMathObject$fromJSON(jsonlite::toJSON(GenericModelObject$modelMath, auto_unbox = TRUE))
    }
  )
)
