# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Hazard Class
#'
#' @field type 
#' @field name 
#' @field description 
#' @field unit 
#' @field adverseEffect 
#' @field sourceOfContamination 
#' @field benchmarkDose 
#' @field maximumResidueLimit 
#' @field noObservedAdverseAffectLevel 
#' @field lowestObservedAdverseAffectLevel 
#' @field acceptableOperatorsExposureLevel 
#' @field acuteReferenceDose 
#' @field acceptableDailyIntake 
#' @field indSum 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Hazard <- R6::R6Class(
  'Hazard',
  public = list(
    `type` = NULL,
    `name` = NULL,
    `description` = NULL,
    `unit` = NULL,
    `adverseEffect` = NULL,
    `sourceOfContamination` = NULL,
    `benchmarkDose` = NULL,
    `maximumResidueLimit` = NULL,
    `noObservedAdverseAffectLevel` = NULL,
    `lowestObservedAdverseAffectLevel` = NULL,
    `acceptableOperatorsExposureLevel` = NULL,
    `acuteReferenceDose` = NULL,
    `acceptableDailyIntake` = NULL,
    `indSum` = NULL,
    initialize = function(`type`, `name`, `description`, `unit`, `adverseEffect`, `sourceOfContamination`, `benchmarkDose`, `maximumResidueLimit`, `noObservedAdverseAffectLevel`, `lowestObservedAdverseAffectLevel`, `acceptableOperatorsExposureLevel`, `acuteReferenceDose`, `acceptableDailyIntake`, `indSum`){
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`unit`)) {
        stopifnot(is.character(`unit`), length(`unit`) == 1)
        self$`unit` <- `unit`
      }
      if (!missing(`adverseEffect`)) {
        stopifnot(is.character(`adverseEffect`), length(`adverseEffect`) == 1)
        self$`adverseEffect` <- `adverseEffect`
      }
      if (!missing(`sourceOfContamination`)) {
        stopifnot(is.character(`sourceOfContamination`), length(`sourceOfContamination`) == 1)
        self$`sourceOfContamination` <- `sourceOfContamination`
      }
      if (!missing(`benchmarkDose`)) {
        stopifnot(is.character(`benchmarkDose`), length(`benchmarkDose`) == 1)
        self$`benchmarkDose` <- `benchmarkDose`
      }
      if (!missing(`maximumResidueLimit`)) {
        stopifnot(is.character(`maximumResidueLimit`), length(`maximumResidueLimit`) == 1)
        self$`maximumResidueLimit` <- `maximumResidueLimit`
      }
      if (!missing(`noObservedAdverseAffectLevel`)) {
        stopifnot(is.character(`noObservedAdverseAffectLevel`), length(`noObservedAdverseAffectLevel`) == 1)
        self$`noObservedAdverseAffectLevel` <- `noObservedAdverseAffectLevel`
      }
      if (!missing(`lowestObservedAdverseAffectLevel`)) {
        stopifnot(is.character(`lowestObservedAdverseAffectLevel`), length(`lowestObservedAdverseAffectLevel`) == 1)
        self$`lowestObservedAdverseAffectLevel` <- `lowestObservedAdverseAffectLevel`
      }
      if (!missing(`acceptableOperatorsExposureLevel`)) {
        stopifnot(is.character(`acceptableOperatorsExposureLevel`), length(`acceptableOperatorsExposureLevel`) == 1)
        self$`acceptableOperatorsExposureLevel` <- `acceptableOperatorsExposureLevel`
      }
      if (!missing(`acuteReferenceDose`)) {
        stopifnot(is.character(`acuteReferenceDose`), length(`acuteReferenceDose`) == 1)
        self$`acuteReferenceDose` <- `acuteReferenceDose`
      }
      if (!missing(`acceptableDailyIntake`)) {
        stopifnot(is.character(`acceptableDailyIntake`), length(`acceptableDailyIntake`) == 1)
        self$`acceptableDailyIntake` <- `acceptableDailyIntake`
      }
      if (!missing(`indSum`)) {
        stopifnot(is.character(`indSum`), length(`indSum`) == 1)
        self$`indSum` <- `indSum`
      }
    },
    toJSON = function() {
      HazardObject <- list()
      if (!is.null(self$`type`)) {
        HazardObject[['type']] <- self$`type`
      }
      if (!is.null(self$`name`)) {
        HazardObject[['name']] <- self$`name`
      }
      if (!is.null(self$`description`)) {
        HazardObject[['description']] <- self$`description`
      }
      if (!is.null(self$`unit`)) {
        HazardObject[['unit']] <- self$`unit`
      }
      if (!is.null(self$`adverseEffect`)) {
        HazardObject[['adverseEffect']] <- self$`adverseEffect`
      }
      if (!is.null(self$`sourceOfContamination`)) {
        HazardObject[['sourceOfContamination']] <- self$`sourceOfContamination`
      }
      if (!is.null(self$`benchmarkDose`)) {
        HazardObject[['benchmarkDose']] <- self$`benchmarkDose`
      }
      if (!is.null(self$`maximumResidueLimit`)) {
        HazardObject[['maximumResidueLimit']] <- self$`maximumResidueLimit`
      }
      if (!is.null(self$`noObservedAdverseAffectLevel`)) {
        HazardObject[['noObservedAdverseAffectLevel']] <- self$`noObservedAdverseAffectLevel`
      }
      if (!is.null(self$`lowestObservedAdverseAffectLevel`)) {
        HazardObject[['lowestObservedAdverseAffectLevel']] <- self$`lowestObservedAdverseAffectLevel`
      }
      if (!is.null(self$`acceptableOperatorsExposureLevel`)) {
        HazardObject[['acceptableOperatorsExposureLevel']] <- self$`acceptableOperatorsExposureLevel`
      }
      if (!is.null(self$`acuteReferenceDose`)) {
        HazardObject[['acuteReferenceDose']] <- self$`acuteReferenceDose`
      }
      if (!is.null(self$`acceptableDailyIntake`)) {
        HazardObject[['acceptableDailyIntake']] <- self$`acceptableDailyIntake`
      }
      if (!is.null(self$`indSum`)) {
        HazardObject[['indSum']] <- self$`indSum`
      }

      HazardObject
    },
    fromJSON = function(HazardJson) {
      HazardObject <- jsonlite::fromJSON(HazardJson)
      if (!is.null(HazardObject$`type`)) {
        self$`type` <- HazardObject$`type`
      }
      if (!is.null(HazardObject$`name`)) {
        self$`name` <- HazardObject$`name`
      }
      if (!is.null(HazardObject$`description`)) {
        self$`description` <- HazardObject$`description`
      }
      if (!is.null(HazardObject$`unit`)) {
        self$`unit` <- HazardObject$`unit`
      }
      if (!is.null(HazardObject$`adverseEffect`)) {
        self$`adverseEffect` <- HazardObject$`adverseEffect`
      }
      if (!is.null(HazardObject$`sourceOfContamination`)) {
        self$`sourceOfContamination` <- HazardObject$`sourceOfContamination`
      }
      if (!is.null(HazardObject$`benchmarkDose`)) {
        self$`benchmarkDose` <- HazardObject$`benchmarkDose`
      }
      if (!is.null(HazardObject$`maximumResidueLimit`)) {
        self$`maximumResidueLimit` <- HazardObject$`maximumResidueLimit`
      }
      if (!is.null(HazardObject$`noObservedAdverseAffectLevel`)) {
        self$`noObservedAdverseAffectLevel` <- HazardObject$`noObservedAdverseAffectLevel`
      }
      if (!is.null(HazardObject$`lowestObservedAdverseAffectLevel`)) {
        self$`lowestObservedAdverseAffectLevel` <- HazardObject$`lowestObservedAdverseAffectLevel`
      }
      if (!is.null(HazardObject$`acceptableOperatorsExposureLevel`)) {
        self$`acceptableOperatorsExposureLevel` <- HazardObject$`acceptableOperatorsExposureLevel`
      }
      if (!is.null(HazardObject$`acuteReferenceDose`)) {
        self$`acuteReferenceDose` <- HazardObject$`acuteReferenceDose`
      }
      if (!is.null(HazardObject$`acceptableDailyIntake`)) {
        self$`acceptableDailyIntake` <- HazardObject$`acceptableDailyIntake`
      }
      if (!is.null(HazardObject$`indSum`)) {
        self$`indSum` <- HazardObject$`indSum`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "type": %s,
           "name": %s,
           "description": %s,
           "unit": %s,
           "adverseEffect": %s,
           "sourceOfContamination": %s,
           "benchmarkDose": %s,
           "maximumResidueLimit": %s,
           "noObservedAdverseAffectLevel": %s,
           "lowestObservedAdverseAffectLevel": %s,
           "acceptableOperatorsExposureLevel": %s,
           "acuteReferenceDose": %s,
           "acceptableDailyIntake": %s,
           "indSum": %s
        }',
        self$`type`,
        self$`name`,
        self$`description`,
        self$`unit`,
        self$`adverseEffect`,
        self$`sourceOfContamination`,
        self$`benchmarkDose`,
        self$`maximumResidueLimit`,
        self$`noObservedAdverseAffectLevel`,
        self$`lowestObservedAdverseAffectLevel`,
        self$`acceptableOperatorsExposureLevel`,
        self$`acuteReferenceDose`,
        self$`acceptableDailyIntake`,
        self$`indSum`
      )
    },
    fromJSONString = function(HazardJson) {
      HazardObject <- jsonlite::fromJSON(HazardJson)
      self$`type` <- HazardObject$`type`
      self$`name` <- HazardObject$`name`
      self$`description` <- HazardObject$`description`
      self$`unit` <- HazardObject$`unit`
      self$`adverseEffect` <- HazardObject$`adverseEffect`
      self$`sourceOfContamination` <- HazardObject$`sourceOfContamination`
      self$`benchmarkDose` <- HazardObject$`benchmarkDose`
      self$`maximumResidueLimit` <- HazardObject$`maximumResidueLimit`
      self$`noObservedAdverseAffectLevel` <- HazardObject$`noObservedAdverseAffectLevel`
      self$`lowestObservedAdverseAffectLevel` <- HazardObject$`lowestObservedAdverseAffectLevel`
      self$`acceptableOperatorsExposureLevel` <- HazardObject$`acceptableOperatorsExposureLevel`
      self$`acuteReferenceDose` <- HazardObject$`acuteReferenceDose`
      self$`acceptableDailyIntake` <- HazardObject$`acceptableDailyIntake`
      self$`indSum` <- HazardObject$`indSum`
    }
  )
)
