# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' HealthModel Class
#'
#' @field modelType 
#' @field generalInformation 
#' @field scope 
#' @field dataBackground 
#' @field modelMath 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
HealthModel <- R6::R6Class(
  'HealthModel',
  public = list(
    `modelType` = NULL,
    `generalInformation` = NULL,
    `scope` = NULL,
    `dataBackground` = NULL,
    `modelMath` = NULL,
    initialize = function(`modelType`, `generalInformation`, `scope`, `dataBackground`, `modelMath`){
      if (!missing(`modelType`)) {
        stopifnot(is.character(`modelType`), length(`modelType`) == 1)
        self$`modelType` <- `modelType`
      }
      if (!missing(`generalInformation`)) {
        stopifnot(R6::is.R6(`generalInformation`))
        self$`generalInformation` <- `generalInformation`
      }
      if (!missing(`scope`)) {
        stopifnot(R6::is.R6(`scope`))
        self$`scope` <- `scope`
      }
      if (!missing(`dataBackground`)) {
        stopifnot(R6::is.R6(`dataBackground`))
        self$`dataBackground` <- `dataBackground`
      }
      if (!missing(`modelMath`)) {
        stopifnot(R6::is.R6(`modelMath`))
        self$`modelMath` <- `modelMath`
      }
    },
    toJSON = function() {
      HealthModelObject <- list()
      if (!is.null(self$`modelType`)) {
        HealthModelObject[['modelType']] <- self$`modelType`
      }
      if (!is.null(self$`generalInformation`)) {
        HealthModelObject[['generalInformation']] <- self$`generalInformation`$toJSON()
      }
      if (!is.null(self$`scope`)) {
        HealthModelObject[['scope']] <- self$`scope`$toJSON()
      }
      if (!is.null(self$`dataBackground`)) {
        HealthModelObject[['dataBackground']] <- self$`dataBackground`$toJSON()
      }
      if (!is.null(self$`modelMath`)) {
        HealthModelObject[['modelMath']] <- self$`modelMath`$toJSON()
      }

      HealthModelObject
    },
    fromJSON = function(HealthModelJson) {
      HealthModelObject <- jsonlite::fromJSON(HealthModelJson)
      if (!is.null(HealthModelObject$`modelType`)) {
        self$`modelType` <- HealthModelObject$`modelType`
      }
      if (!is.null(HealthModelObject$`generalInformation`)) {
        generalInformationObject <- PredictiveModelGeneralInformation$new()
        generalInformationObject$fromJSON(jsonlite::toJSON(HealthModelObject$generalInformation, auto_unbox = TRUE))
        self$`generalInformation` <- generalInformationObject
      }
      if (!is.null(HealthModelObject$`scope`)) {
        scopeObject <- HealthModelScope$new()
        scopeObject$fromJSON(jsonlite::toJSON(HealthModelObject$scope, auto_unbox = TRUE))
        self$`scope` <- scopeObject
      }
      if (!is.null(HealthModelObject$`dataBackground`)) {
        dataBackgroundObject <- PredictiveModelDataBackground$new()
        dataBackgroundObject$fromJSON(jsonlite::toJSON(HealthModelObject$dataBackground, auto_unbox = TRUE))
        self$`dataBackground` <- dataBackgroundObject
      }
      if (!is.null(HealthModelObject$`modelMath`)) {
        modelMathObject <- GenericModelModelMath$new()
        modelMathObject$fromJSON(jsonlite::toJSON(HealthModelObject$modelMath, auto_unbox = TRUE))
        self$`modelMath` <- modelMathObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "modelType": %s,
           "generalInformation": %s,
           "scope": %s,
           "dataBackground": %s,
           "modelMath": %s
        }',
        self$`modelType`,
        self$`generalInformation`$toJSON(),
        self$`scope`$toJSON(),
        self$`dataBackground`$toJSON(),
        self$`modelMath`$toJSON()
      )
    },
    fromJSONString = function(HealthModelJson) {
      HealthModelObject <- jsonlite::fromJSON(HealthModelJson)
      self$`modelType` <- HealthModelObject$`modelType`
      PredictiveModelGeneralInformationObject <- PredictiveModelGeneralInformation$new()
      self$`generalInformation` <- PredictiveModelGeneralInformationObject$fromJSON(jsonlite::toJSON(HealthModelObject$generalInformation, auto_unbox = TRUE))
      HealthModelScopeObject <- HealthModelScope$new()
      self$`scope` <- HealthModelScopeObject$fromJSON(jsonlite::toJSON(HealthModelObject$scope, auto_unbox = TRUE))
      PredictiveModelDataBackgroundObject <- PredictiveModelDataBackground$new()
      self$`dataBackground` <- PredictiveModelDataBackgroundObject$fromJSON(jsonlite::toJSON(HealthModelObject$dataBackground, auto_unbox = TRUE))
      GenericModelModelMathObject <- GenericModelModelMath$new()
      self$`modelMath` <- GenericModelModelMathObject$fromJSON(jsonlite::toJSON(HealthModelObject$modelMath, auto_unbox = TRUE))
    }
  )
)
