# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' HealthModelScope Class
#'
#' @field hazard 
#' @field populationGroup 
#' @field generalComment 
#' @field temporalInformation 
#' @field spatialInformation 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
HealthModelScope <- R6::R6Class(
  'HealthModelScope',
  public = list(
    `hazard` = NULL,
    `populationGroup` = NULL,
    `generalComment` = NULL,
    `temporalInformation` = NULL,
    `spatialInformation` = NULL,
    initialize = function(`hazard`, `populationGroup`, `generalComment`, `temporalInformation`, `spatialInformation`){
      if (!missing(`hazard`)) {
        stopifnot(is.list(`hazard`), length(`hazard`) != 0)
        lapply(`hazard`, function(x) stopifnot(R6::is.R6(x)))
        self$`hazard` <- `hazard`
      }
      if (!missing(`populationGroup`)) {
        stopifnot(is.list(`populationGroup`), length(`populationGroup`) != 0)
        lapply(`populationGroup`, function(x) stopifnot(R6::is.R6(x)))
        self$`populationGroup` <- `populationGroup`
      }
      if (!missing(`generalComment`)) {
        stopifnot(is.character(`generalComment`), length(`generalComment`) == 1)
        self$`generalComment` <- `generalComment`
      }
      if (!missing(`temporalInformation`)) {
        stopifnot(is.character(`temporalInformation`), length(`temporalInformation`) == 1)
        self$`temporalInformation` <- `temporalInformation`
      }
      if (!missing(`spatialInformation`)) {
        stopifnot(is.list(`spatialInformation`), length(`spatialInformation`) != 0)
        lapply(`spatialInformation`, function(x) stopifnot(is.character(x)))
        self$`spatialInformation` <- `spatialInformation`
      }
    },
    toJSON = function() {
      HealthModelScopeObject <- list()
      if (!is.null(self$`hazard`)) {
        HealthModelScopeObject[['hazard']] <- lapply(self$`hazard`, function(x) x$toJSON())
      }
      if (!is.null(self$`populationGroup`)) {
        HealthModelScopeObject[['populationGroup']] <- lapply(self$`populationGroup`, function(x) x$toJSON())
      }
      if (!is.null(self$`generalComment`)) {
        HealthModelScopeObject[['generalComment']] <- self$`generalComment`
      }
      if (!is.null(self$`temporalInformation`)) {
        HealthModelScopeObject[['temporalInformation']] <- self$`temporalInformation`
      }
      if (!is.null(self$`spatialInformation`)) {
        HealthModelScopeObject[['spatialInformation']] <- self$`spatialInformation`
      }

      HealthModelScopeObject
    },
    fromJSON = function(HealthModelScopeJson) {
      HealthModelScopeObject <- jsonlite::fromJSON(HealthModelScopeJson)
      if (!is.null(HealthModelScopeObject$`hazard`)) {
        self$`hazard` <- lapply(HealthModelScopeObject$`hazard`, function(x) {
          hazardObject <- Hazard$new()
          hazardObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          hazardObject
        })
      }
      if (!is.null(HealthModelScopeObject$`populationGroup`)) {
        self$`populationGroup` <- lapply(HealthModelScopeObject$`populationGroup`, function(x) {
          populationGroupObject <- PopulationGroup$new()
          populationGroupObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          populationGroupObject
        })
      }
      if (!is.null(HealthModelScopeObject$`generalComment`)) {
        self$`generalComment` <- HealthModelScopeObject$`generalComment`
      }
      if (!is.null(HealthModelScopeObject$`temporalInformation`)) {
        self$`temporalInformation` <- HealthModelScopeObject$`temporalInformation`
      }
      if (!is.null(HealthModelScopeObject$`spatialInformation`)) {
        self$`spatialInformation` <- HealthModelScopeObject$`spatialInformation`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "hazard": [%s],
           "populationGroup": [%s],
           "generalComment": %s,
           "temporalInformation": %s,
           "spatialInformation": [%s]
        }',
        lapply(self$`hazard`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`populationGroup`, function(x) paste(x$toJSON(), sep=",")),
        self$`generalComment`,
        self$`temporalInformation`,
        lapply(self$`spatialInformation`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(HealthModelScopeJson) {
      HealthModelScopeObject <- jsonlite::fromJSON(HealthModelScopeJson)
      self$`hazard` <- lapply(HealthModelScopeObject$`hazard`, function(x) Hazard$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`populationGroup` <- lapply(HealthModelScopeObject$`populationGroup`, function(x) PopulationGroup$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`generalComment` <- HealthModelScopeObject$`generalComment`
      self$`temporalInformation` <- HealthModelScopeObject$`temporalInformation`
      self$`spatialInformation` <- HealthModelScopeObject$`spatialInformation`
    }
  )
)
