# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Laboratory Class
#'
#' @field accreditation 
#' @field name 
#' @field country 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Laboratory <- R6::R6Class(
  'Laboratory',
  public = list(
    `accreditation` = NULL,
    `name` = NULL,
    `country` = NULL,
    initialize = function(`accreditation`, `name`, `country`){
      if (!missing(`accreditation`)) {
        stopifnot(is.list(`accreditation`), length(`accreditation`) != 0)
        lapply(`accreditation`, function(x) stopifnot(is.character(x)))
        self$`accreditation` <- `accreditation`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`country`)) {
        stopifnot(is.character(`country`), length(`country`) == 1)
        self$`country` <- `country`
      }
    },
    toJSON = function() {
      LaboratoryObject <- list()
      if (!is.null(self$`accreditation`)) {
        LaboratoryObject[['accreditation']] <- self$`accreditation`
      }
      if (!is.null(self$`name`)) {
        LaboratoryObject[['name']] <- self$`name`
      }
      if (!is.null(self$`country`)) {
        LaboratoryObject[['country']] <- self$`country`
      }

      LaboratoryObject
    },
    fromJSON = function(LaboratoryJson) {
      LaboratoryObject <- jsonlite::fromJSON(LaboratoryJson)
      if (!is.null(LaboratoryObject$`accreditation`)) {
        self$`accreditation` <- LaboratoryObject$`accreditation`
      }
      if (!is.null(LaboratoryObject$`name`)) {
        self$`name` <- LaboratoryObject$`name`
      }
      if (!is.null(LaboratoryObject$`country`)) {
        self$`country` <- LaboratoryObject$`country`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "accreditation": [%s],
           "name": %s,
           "country": %s
        }',
        lapply(self$`accreditation`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`name`,
        self$`country`
      )
    },
    fromJSONString = function(LaboratoryJson) {
      LaboratoryObject <- jsonlite::fromJSON(LaboratoryJson)
      self$`accreditation` <- LaboratoryObject$`accreditation`
      self$`name` <- LaboratoryObject$`name`
      self$`country` <- LaboratoryObject$`country`
    }
  )
)
