# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' ModelEquation Class
#'
#' @field name 
#' @field class 
#' @field reference 
#' @field modelEquation 
#' @field modelHypothesis 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ModelEquation <- R6::R6Class(
  'ModelEquation',
  public = list(
    `name` = NULL,
    `class` = NULL,
    `reference` = NULL,
    `modelEquation` = NULL,
    `modelHypothesis` = NULL,
    initialize = function(`name`, `class`, `reference`, `modelEquation`, `modelHypothesis`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`class`)) {
        stopifnot(is.character(`class`), length(`class`) == 1)
        self$`class` <- `class`
      }
      if (!missing(`reference`)) {
        stopifnot(is.list(`reference`), length(`reference`) != 0)
        lapply(`reference`, function(x) stopifnot(R6::is.R6(x)))
        self$`reference` <- `reference`
      }
      if (!missing(`modelEquation`)) {
        stopifnot(is.character(`modelEquation`), length(`modelEquation`) == 1)
        self$`modelEquation` <- `modelEquation`
      }
      if (!missing(`modelHypothesis`)) {
        stopifnot(is.list(`modelHypothesis`), length(`modelHypothesis`) != 0)
        lapply(`modelHypothesis`, function(x) stopifnot(is.character(x)))
        self$`modelHypothesis` <- `modelHypothesis`
      }
    },
    toJSON = function() {
      ModelEquationObject <- list()
      if (!is.null(self$`name`)) {
        ModelEquationObject[['name']] <- self$`name`
      }
      if (!is.null(self$`class`)) {
        ModelEquationObject[['class']] <- self$`class`
      }
      if (!is.null(self$`reference`)) {
        ModelEquationObject[['reference']] <- lapply(self$`reference`, function(x) x$toJSON())
      }
      if (!is.null(self$`modelEquation`)) {
        ModelEquationObject[['modelEquation']] <- self$`modelEquation`
      }
      if (!is.null(self$`modelHypothesis`)) {
        ModelEquationObject[['modelHypothesis']] <- self$`modelHypothesis`
      }

      ModelEquationObject
    },
    fromJSON = function(ModelEquationJson) {
      ModelEquationObject <- jsonlite::fromJSON(ModelEquationJson)
      if (!is.null(ModelEquationObject$`name`)) {
        self$`name` <- ModelEquationObject$`name`
      }
      if (!is.null(ModelEquationObject$`class`)) {
        self$`class` <- ModelEquationObject$`class`
      }
      if (!is.null(ModelEquationObject$`reference`)) {
        self$`reference` <- lapply(ModelEquationObject$`reference`, function(x) {
          referenceObject <- Reference$new()
          referenceObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          referenceObject
        })
      }
      if (!is.null(ModelEquationObject$`modelEquation`)) {
        self$`modelEquation` <- ModelEquationObject$`modelEquation`
      }
      if (!is.null(ModelEquationObject$`modelHypothesis`)) {
        self$`modelHypothesis` <- ModelEquationObject$`modelHypothesis`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "class": %s,
           "reference": [%s],
           "modelEquation": %s,
           "modelHypothesis": [%s]
        }',
        self$`name`,
        self$`class`,
        lapply(self$`reference`, function(x) paste(x$toJSON(), sep=",")),
        self$`modelEquation`,
        lapply(self$`modelHypothesis`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(ModelEquationJson) {
      ModelEquationObject <- jsonlite::fromJSON(ModelEquationJson)
      self$`name` <- ModelEquationObject$`name`
      self$`class` <- ModelEquationObject$`class`
      self$`reference` <- lapply(ModelEquationObject$`reference`, function(x) Reference$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`modelEquation` <- ModelEquationObject$`modelEquation`
      self$`modelHypothesis` <- ModelEquationObject$`modelHypothesis`
    }
  )
)
