# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Parameter Class
#'
#' @field id 
#' @field classification 
#' @field name 
#' @field description 
#' @field unit 
#' @field unitCategory 
#' @field dataType 
#' @field source 
#' @field subject 
#' @field distribution 
#' @field value 
#' @field reference 
#' @field variabilitySubject 
#' @field minValue 
#' @field maxValue 
#' @field error 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Parameter <- R6::R6Class(
  'Parameter',
  public = list(
    `id` = NULL,
    `classification` = NULL,
    `name` = NULL,
    `description` = NULL,
    `unit` = NULL,
    `unitCategory` = NULL,
    `dataType` = NULL,
    `source` = NULL,
    `subject` = NULL,
    `distribution` = NULL,
    `value` = NULL,
    `reference` = NULL,
    `variabilitySubject` = NULL,
    `minValue` = NULL,
    `maxValue` = NULL,
    `error` = NULL,
    initialize = function(`id`, `classification`, `name`, `description`, `unit`, `unitCategory`, `dataType`, `source`, `subject`, `distribution`, `value`, `reference`, `variabilitySubject`, `minValue`, `maxValue`, `error`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`classification`)) {
        stopifnot(is.character(`classification`), length(`classification`) == 1)
        self$`classification` <- `classification`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`unit`)) {
        stopifnot(is.character(`unit`), length(`unit`) == 1)
        self$`unit` <- `unit`
      }
      if (!missing(`unitCategory`)) {
        stopifnot(is.character(`unitCategory`), length(`unitCategory`) == 1)
        self$`unitCategory` <- `unitCategory`
      }
      if (!missing(`dataType`)) {
        stopifnot(is.character(`dataType`), length(`dataType`) == 1)
        self$`dataType` <- `dataType`
      }
      if (!missing(`source`)) {
        stopifnot(is.character(`source`), length(`source`) == 1)
        self$`source` <- `source`
      }
      if (!missing(`subject`)) {
        stopifnot(is.character(`subject`), length(`subject`) == 1)
        self$`subject` <- `subject`
      }
      if (!missing(`distribution`)) {
        stopifnot(is.character(`distribution`), length(`distribution`) == 1)
        self$`distribution` <- `distribution`
      }
      if (!missing(`value`)) {
        stopifnot(is.character(`value`), length(`value`) == 1)
        self$`value` <- `value`
      }
      if (!missing(`reference`)) {
        stopifnot(R6::is.R6(`reference`))
        self$`reference` <- `reference`
      }
      if (!missing(`variabilitySubject`)) {
        stopifnot(is.character(`variabilitySubject`), length(`variabilitySubject`) == 1)
        self$`variabilitySubject` <- `variabilitySubject`
      }
      if (!missing(`minValue`)) {
        stopifnot(is.character(`minValue`), length(`minValue`) == 1)
        self$`minValue` <- `minValue`
      }
      if (!missing(`maxValue`)) {
        stopifnot(is.character(`maxValue`), length(`maxValue`) == 1)
        self$`maxValue` <- `maxValue`
      }
      if (!missing(`error`)) {
        stopifnot(is.character(`error`), length(`error`) == 1)
        self$`error` <- `error`
      }
    },
    toJSON = function() {
      ParameterObject <- list()
      if (!is.null(self$`id`)) {
        ParameterObject[['id']] <- self$`id`
      }
      if (!is.null(self$`classification`)) {
        ParameterObject[['classification']] <- self$`classification`
      }
      if (!is.null(self$`name`)) {
        ParameterObject[['name']] <- self$`name`
      }
      if (!is.null(self$`description`)) {
        ParameterObject[['description']] <- self$`description`
      }
      if (!is.null(self$`unit`)) {
        ParameterObject[['unit']] <- self$`unit`
      }
      if (!is.null(self$`unitCategory`)) {
        ParameterObject[['unitCategory']] <- self$`unitCategory`
      }
      if (!is.null(self$`dataType`)) {
        ParameterObject[['dataType']] <- self$`dataType`
      }
      if (!is.null(self$`source`)) {
        ParameterObject[['source']] <- self$`source`
      }
      if (!is.null(self$`subject`)) {
        ParameterObject[['subject']] <- self$`subject`
      }
      if (!is.null(self$`distribution`)) {
        ParameterObject[['distribution']] <- self$`distribution`
      }
      if (!is.null(self$`value`)) {
        ParameterObject[['value']] <- self$`value`
      }
      if (!is.null(self$`reference`)) {
        ParameterObject[['reference']] <- self$`reference`$toJSON()
      }
      if (!is.null(self$`variabilitySubject`)) {
        ParameterObject[['variabilitySubject']] <- self$`variabilitySubject`
      }
      if (!is.null(self$`minValue`)) {
        ParameterObject[['minValue']] <- self$`minValue`
      }
      if (!is.null(self$`maxValue`)) {
        ParameterObject[['maxValue']] <- self$`maxValue`
      }
      if (!is.null(self$`error`)) {
        ParameterObject[['error']] <- self$`error`
      }

      ParameterObject
    },
    fromJSON = function(ParameterJson) {
      ParameterObject <- jsonlite::fromJSON(ParameterJson)
      if (!is.null(ParameterObject$`id`)) {
        self$`id` <- ParameterObject$`id`
      }
      if (!is.null(ParameterObject$`classification`)) {
        self$`classification` <- ParameterObject$`classification`
      }
      if (!is.null(ParameterObject$`name`)) {
        self$`name` <- ParameterObject$`name`
      }
      if (!is.null(ParameterObject$`description`)) {
        self$`description` <- ParameterObject$`description`
      }
      if (!is.null(ParameterObject$`unit`)) {
        self$`unit` <- ParameterObject$`unit`
      }
      if (!is.null(ParameterObject$`unitCategory`)) {
        self$`unitCategory` <- ParameterObject$`unitCategory`
      }
      if (!is.null(ParameterObject$`dataType`)) {
        self$`dataType` <- ParameterObject$`dataType`
      }
      if (!is.null(ParameterObject$`source`)) {
        self$`source` <- ParameterObject$`source`
      }
      if (!is.null(ParameterObject$`subject`)) {
        self$`subject` <- ParameterObject$`subject`
      }
      if (!is.null(ParameterObject$`distribution`)) {
        self$`distribution` <- ParameterObject$`distribution`
      }
      if (!is.null(ParameterObject$`value`)) {
        self$`value` <- ParameterObject$`value`
      }
      if (!is.null(ParameterObject$`reference`)) {
        referenceObject <- Reference$new()
        referenceObject$fromJSON(jsonlite::toJSON(ParameterObject$reference, auto_unbox = TRUE))
        self$`reference` <- referenceObject
      }
      if (!is.null(ParameterObject$`variabilitySubject`)) {
        self$`variabilitySubject` <- ParameterObject$`variabilitySubject`
      }
      if (!is.null(ParameterObject$`minValue`)) {
        self$`minValue` <- ParameterObject$`minValue`
      }
      if (!is.null(ParameterObject$`maxValue`)) {
        self$`maxValue` <- ParameterObject$`maxValue`
      }
      if (!is.null(ParameterObject$`error`)) {
        self$`error` <- ParameterObject$`error`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "classification": %s,
           "name": %s,
           "description": %s,
           "unit": %s,
           "unitCategory": %s,
           "dataType": %s,
           "source": %s,
           "subject": %s,
           "distribution": %s,
           "value": %s,
           "reference": %s,
           "variabilitySubject": %s,
           "minValue": %s,
           "maxValue": %s,
           "error": %s
        }',
        self$`id`,
        self$`classification`,
        self$`name`,
        self$`description`,
        self$`unit`,
        self$`unitCategory`,
        self$`dataType`,
        self$`source`,
        self$`subject`,
        self$`distribution`,
        self$`value`,
        self$`reference`$toJSON(),
        self$`variabilitySubject`,
        self$`minValue`,
        self$`maxValue`,
        self$`error`
      )
    },
    fromJSONString = function(ParameterJson) {
      ParameterObject <- jsonlite::fromJSON(ParameterJson)
      self$`id` <- ParameterObject$`id`
      self$`classification` <- ParameterObject$`classification`
      self$`name` <- ParameterObject$`name`
      self$`description` <- ParameterObject$`description`
      self$`unit` <- ParameterObject$`unit`
      self$`unitCategory` <- ParameterObject$`unitCategory`
      self$`dataType` <- ParameterObject$`dataType`
      self$`source` <- ParameterObject$`source`
      self$`subject` <- ParameterObject$`subject`
      self$`distribution` <- ParameterObject$`distribution`
      self$`value` <- ParameterObject$`value`
      ReferenceObject <- Reference$new()
      self$`reference` <- ReferenceObject$fromJSON(jsonlite::toJSON(ParameterObject$reference, auto_unbox = TRUE))
      self$`variabilitySubject` <- ParameterObject$`variabilitySubject`
      self$`minValue` <- ParameterObject$`minValue`
      self$`maxValue` <- ParameterObject$`maxValue`
      self$`error` <- ParameterObject$`error`
    }
  )
)
