# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' PredictiveModelScopeProduct Class
#'
#' @field name 
#' @field description 
#' @field unit 
#' @field method 
#' @field packaging 
#' @field treatment 
#' @field originCountry 
#' @field originArea 
#' @field fisheriesArea 
#' @field productionDate 
#' @field expiryDate 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PredictiveModelScopeProduct <- R6::R6Class(
  'PredictiveModelScopeProduct',
  public = list(
    `name` = NULL,
    `description` = NULL,
    `unit` = NULL,
    `method` = NULL,
    `packaging` = NULL,
    `treatment` = NULL,
    `originCountry` = NULL,
    `originArea` = NULL,
    `fisheriesArea` = NULL,
    `productionDate` = NULL,
    `expiryDate` = NULL,
    initialize = function(`name`, `description`, `unit`, `method`, `packaging`, `treatment`, `originCountry`, `originArea`, `fisheriesArea`, `productionDate`, `expiryDate`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`unit`)) {
        stopifnot(is.character(`unit`), length(`unit`) == 1)
        self$`unit` <- `unit`
      }
      if (!missing(`method`)) {
        stopifnot(is.list(`method`), length(`method`) != 0)
        lapply(`method`, function(x) stopifnot(is.character(x)))
        self$`method` <- `method`
      }
      if (!missing(`packaging`)) {
        stopifnot(is.list(`packaging`), length(`packaging`) != 0)
        lapply(`packaging`, function(x) stopifnot(is.character(x)))
        self$`packaging` <- `packaging`
      }
      if (!missing(`treatment`)) {
        stopifnot(is.list(`treatment`), length(`treatment`) != 0)
        lapply(`treatment`, function(x) stopifnot(is.character(x)))
        self$`treatment` <- `treatment`
      }
      if (!missing(`originCountry`)) {
        stopifnot(is.character(`originCountry`), length(`originCountry`) == 1)
        self$`originCountry` <- `originCountry`
      }
      if (!missing(`originArea`)) {
        stopifnot(is.character(`originArea`), length(`originArea`) == 1)
        self$`originArea` <- `originArea`
      }
      if (!missing(`fisheriesArea`)) {
        stopifnot(is.character(`fisheriesArea`), length(`fisheriesArea`) == 1)
        self$`fisheriesArea` <- `fisheriesArea`
      }
      if (!missing(`productionDate`)) {
        stopifnot(is.character(`productionDate`), length(`productionDate`) == 1)
        self$`productionDate` <- `productionDate`
      }
      if (!missing(`expiryDate`)) {
        stopifnot(is.character(`expiryDate`), length(`expiryDate`) == 1)
        self$`expiryDate` <- `expiryDate`
      }
    },
    toJSON = function() {
      PredictiveModelScopeProductObject <- list()
      if (!is.null(self$`name`)) {
        PredictiveModelScopeProductObject[['name']] <- self$`name`
      }
      if (!is.null(self$`description`)) {
        PredictiveModelScopeProductObject[['description']] <- self$`description`
      }
      if (!is.null(self$`unit`)) {
        PredictiveModelScopeProductObject[['unit']] <- self$`unit`
      }
      if (!is.null(self$`method`)) {
        PredictiveModelScopeProductObject[['method']] <- self$`method`
      }
      if (!is.null(self$`packaging`)) {
        PredictiveModelScopeProductObject[['packaging']] <- self$`packaging`
      }
      if (!is.null(self$`treatment`)) {
        PredictiveModelScopeProductObject[['treatment']] <- self$`treatment`
      }
      if (!is.null(self$`originCountry`)) {
        PredictiveModelScopeProductObject[['originCountry']] <- self$`originCountry`
      }
      if (!is.null(self$`originArea`)) {
        PredictiveModelScopeProductObject[['originArea']] <- self$`originArea`
      }
      if (!is.null(self$`fisheriesArea`)) {
        PredictiveModelScopeProductObject[['fisheriesArea']] <- self$`fisheriesArea`
      }
      if (!is.null(self$`productionDate`)) {
        PredictiveModelScopeProductObject[['productionDate']] <- self$`productionDate`
      }
      if (!is.null(self$`expiryDate`)) {
        PredictiveModelScopeProductObject[['expiryDate']] <- self$`expiryDate`
      }

      PredictiveModelScopeProductObject
    },
    fromJSON = function(PredictiveModelScopeProductJson) {
      PredictiveModelScopeProductObject <- jsonlite::fromJSON(PredictiveModelScopeProductJson)
      if (!is.null(PredictiveModelScopeProductObject$`name`)) {
        self$`name` <- PredictiveModelScopeProductObject$`name`
      }
      if (!is.null(PredictiveModelScopeProductObject$`description`)) {
        self$`description` <- PredictiveModelScopeProductObject$`description`
      }
      if (!is.null(PredictiveModelScopeProductObject$`unit`)) {
        self$`unit` <- PredictiveModelScopeProductObject$`unit`
      }
      if (!is.null(PredictiveModelScopeProductObject$`method`)) {
        self$`method` <- PredictiveModelScopeProductObject$`method`
      }
      if (!is.null(PredictiveModelScopeProductObject$`packaging`)) {
        self$`packaging` <- PredictiveModelScopeProductObject$`packaging`
      }
      if (!is.null(PredictiveModelScopeProductObject$`treatment`)) {
        self$`treatment` <- PredictiveModelScopeProductObject$`treatment`
      }
      if (!is.null(PredictiveModelScopeProductObject$`originCountry`)) {
        self$`originCountry` <- PredictiveModelScopeProductObject$`originCountry`
      }
      if (!is.null(PredictiveModelScopeProductObject$`originArea`)) {
        self$`originArea` <- PredictiveModelScopeProductObject$`originArea`
      }
      if (!is.null(PredictiveModelScopeProductObject$`fisheriesArea`)) {
        self$`fisheriesArea` <- PredictiveModelScopeProductObject$`fisheriesArea`
      }
      if (!is.null(PredictiveModelScopeProductObject$`productionDate`)) {
        self$`productionDate` <- PredictiveModelScopeProductObject$`productionDate`
      }
      if (!is.null(PredictiveModelScopeProductObject$`expiryDate`)) {
        self$`expiryDate` <- PredictiveModelScopeProductObject$`expiryDate`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "description": %s,
           "unit": %s,
           "method": [%s],
           "packaging": [%s],
           "treatment": [%s],
           "originCountry": %s,
           "originArea": %s,
           "fisheriesArea": %s,
           "productionDate": %s,
           "expiryDate": %s
        }',
        self$`name`,
        self$`description`,
        self$`unit`,
        lapply(self$`method`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`packaging`, function(x) paste(paste0('"', x, '"'), sep=",")),
        lapply(self$`treatment`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`originCountry`,
        self$`originArea`,
        self$`fisheriesArea`,
        self$`productionDate`,
        self$`expiryDate`
      )
    },
    fromJSONString = function(PredictiveModelScopeProductJson) {
      PredictiveModelScopeProductObject <- jsonlite::fromJSON(PredictiveModelScopeProductJson)
      self$`name` <- PredictiveModelScopeProductObject$`name`
      self$`description` <- PredictiveModelScopeProductObject$`description`
      self$`unit` <- PredictiveModelScopeProductObject$`unit`
      self$`method` <- PredictiveModelScopeProductObject$`method`
      self$`packaging` <- PredictiveModelScopeProductObject$`packaging`
      self$`treatment` <- PredictiveModelScopeProductObject$`treatment`
      self$`originCountry` <- PredictiveModelScopeProductObject$`originCountry`
      self$`originArea` <- PredictiveModelScopeProductObject$`originArea`
      self$`fisheriesArea` <- PredictiveModelScopeProductObject$`fisheriesArea`
      self$`productionDate` <- PredictiveModelScopeProductObject$`productionDate`
      self$`expiryDate` <- PredictiveModelScopeProductObject$`expiryDate`
    }
  )
)
