# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' PredictiveModelDataBackground Class
#'
#' @field study 
#' @field studySample 
#' @field laboratory 
#' @field assay 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PredictiveModelDataBackground <- R6::R6Class(
  'PredictiveModelDataBackground',
  public = list(
    `study` = NULL,
    `studySample` = NULL,
    `laboratory` = NULL,
    `assay` = NULL,
    initialize = function(`study`, `studySample`, `laboratory`, `assay`){
      if (!missing(`study`)) {
        stopifnot(R6::is.R6(`study`))
        self$`study` <- `study`
      }
      if (!missing(`studySample`)) {
        stopifnot(is.list(`studySample`), length(`studySample`) != 0)
        lapply(`studySample`, function(x) stopifnot(R6::is.R6(x)))
        self$`studySample` <- `studySample`
      }
      if (!missing(`laboratory`)) {
        stopifnot(is.list(`laboratory`), length(`laboratory`) != 0)
        lapply(`laboratory`, function(x) stopifnot(R6::is.R6(x)))
        self$`laboratory` <- `laboratory`
      }
      if (!missing(`assay`)) {
        stopifnot(is.list(`assay`), length(`assay`) != 0)
        lapply(`assay`, function(x) stopifnot(R6::is.R6(x)))
        self$`assay` <- `assay`
      }
    },
    toJSON = function() {
      PredictiveModelDataBackgroundObject <- list()
      if (!is.null(self$`study`)) {
        PredictiveModelDataBackgroundObject[['study']] <- self$`study`$toJSON()
      }
      if (!is.null(self$`studySample`)) {
        PredictiveModelDataBackgroundObject[['studySample']] <- lapply(self$`studySample`, function(x) x$toJSON())
      }
      if (!is.null(self$`laboratory`)) {
        PredictiveModelDataBackgroundObject[['laboratory']] <- lapply(self$`laboratory`, function(x) x$toJSON())
      }
      if (!is.null(self$`assay`)) {
        PredictiveModelDataBackgroundObject[['assay']] <- lapply(self$`assay`, function(x) x$toJSON())
      }

      PredictiveModelDataBackgroundObject
    },
    fromJSON = function(PredictiveModelDataBackgroundJson) {
      PredictiveModelDataBackgroundObject <- jsonlite::fromJSON(PredictiveModelDataBackgroundJson)
      if (!is.null(PredictiveModelDataBackgroundObject$`study`)) {
        studyObject <- Study$new()
        studyObject$fromJSON(jsonlite::toJSON(PredictiveModelDataBackgroundObject$study, auto_unbox = TRUE))
        self$`study` <- studyObject
      }
      if (!is.null(PredictiveModelDataBackgroundObject$`studySample`)) {
        self$`studySample` <- lapply(PredictiveModelDataBackgroundObject$`studySample`, function(x) {
          studySampleObject <- StudySample$new()
          studySampleObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          studySampleObject
        })
      }
      if (!is.null(PredictiveModelDataBackgroundObject$`laboratory`)) {
        self$`laboratory` <- lapply(PredictiveModelDataBackgroundObject$`laboratory`, function(x) {
          laboratoryObject <- Laboratory$new()
          laboratoryObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          laboratoryObject
        })
      }
      if (!is.null(PredictiveModelDataBackgroundObject$`assay`)) {
        self$`assay` <- lapply(PredictiveModelDataBackgroundObject$`assay`, function(x) {
          assayObject <- Assay$new()
          assayObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          assayObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "study": %s,
           "studySample": [%s],
           "laboratory": [%s],
           "assay": [%s]
        }',
        self$`study`$toJSON(),
        lapply(self$`studySample`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`laboratory`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`assay`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(PredictiveModelDataBackgroundJson) {
      PredictiveModelDataBackgroundObject <- jsonlite::fromJSON(PredictiveModelDataBackgroundJson)
      StudyObject <- Study$new()
      self$`study` <- StudyObject$fromJSON(jsonlite::toJSON(PredictiveModelDataBackgroundObject$study, auto_unbox = TRUE))
      self$`studySample` <- lapply(PredictiveModelDataBackgroundObject$`studySample`, function(x) StudySample$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`laboratory` <- lapply(PredictiveModelDataBackgroundObject$`laboratory`, function(x) Laboratory$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`assay` <- lapply(PredictiveModelDataBackgroundObject$`assay`, function(x) Assay$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
