# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' PredictiveModelScope Class
#'
#' @field product 
#' @field hazard 
#' @field generalComment 
#' @field temporalInformation 
#' @field spatialInformation 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PredictiveModelScope <- R6::R6Class(
  'PredictiveModelScope',
  public = list(
    `product` = NULL,
    `hazard` = NULL,
    `generalComment` = NULL,
    `temporalInformation` = NULL,
    `spatialInformation` = NULL,
    initialize = function(`product`, `hazard`, `generalComment`, `temporalInformation`, `spatialInformation`){
      if (!missing(`product`)) {
        stopifnot(is.list(`product`), length(`product`) != 0)
        lapply(`product`, function(x) stopifnot(R6::is.R6(x)))
        self$`product` <- `product`
      }
      if (!missing(`hazard`)) {
        stopifnot(is.list(`hazard`), length(`hazard`) != 0)
        lapply(`hazard`, function(x) stopifnot(R6::is.R6(x)))
        self$`hazard` <- `hazard`
      }
      if (!missing(`generalComment`)) {
        stopifnot(is.character(`generalComment`), length(`generalComment`) == 1)
        self$`generalComment` <- `generalComment`
      }
      if (!missing(`temporalInformation`)) {
        stopifnot(is.character(`temporalInformation`), length(`temporalInformation`) == 1)
        self$`temporalInformation` <- `temporalInformation`
      }
      if (!missing(`spatialInformation`)) {
        stopifnot(is.list(`spatialInformation`), length(`spatialInformation`) != 0)
        lapply(`spatialInformation`, function(x) stopifnot(is.character(x)))
        self$`spatialInformation` <- `spatialInformation`
      }
    },
    toJSON = function() {
      PredictiveModelScopeObject <- list()
      if (!is.null(self$`product`)) {
        PredictiveModelScopeObject[['product']] <- lapply(self$`product`, function(x) x$toJSON())
      }
      if (!is.null(self$`hazard`)) {
        PredictiveModelScopeObject[['hazard']] <- lapply(self$`hazard`, function(x) x$toJSON())
      }
      if (!is.null(self$`generalComment`)) {
        PredictiveModelScopeObject[['generalComment']] <- self$`generalComment`
      }
      if (!is.null(self$`temporalInformation`)) {
        PredictiveModelScopeObject[['temporalInformation']] <- self$`temporalInformation`
      }
      if (!is.null(self$`spatialInformation`)) {
        PredictiveModelScopeObject[['spatialInformation']] <- self$`spatialInformation`
      }

      PredictiveModelScopeObject
    },
    fromJSON = function(PredictiveModelScopeJson) {
      PredictiveModelScopeObject <- jsonlite::fromJSON(PredictiveModelScopeJson)
      if (!is.null(PredictiveModelScopeObject$`product`)) {
        self$`product` <- lapply(PredictiveModelScopeObject$`product`, function(x) {
          productObject <- PredictiveModelScopeProduct$new()
          productObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          productObject
        })
      }
      if (!is.null(PredictiveModelScopeObject$`hazard`)) {
        self$`hazard` <- lapply(PredictiveModelScopeObject$`hazard`, function(x) {
          hazardObject <- Hazard$new()
          hazardObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          hazardObject
        })
      }
      if (!is.null(PredictiveModelScopeObject$`generalComment`)) {
        self$`generalComment` <- PredictiveModelScopeObject$`generalComment`
      }
      if (!is.null(PredictiveModelScopeObject$`temporalInformation`)) {
        self$`temporalInformation` <- PredictiveModelScopeObject$`temporalInformation`
      }
      if (!is.null(PredictiveModelScopeObject$`spatialInformation`)) {
        self$`spatialInformation` <- PredictiveModelScopeObject$`spatialInformation`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "product": [%s],
           "hazard": [%s],
           "generalComment": %s,
           "temporalInformation": %s,
           "spatialInformation": [%s]
        }',
        lapply(self$`product`, function(x) paste(x$toJSON(), sep=",")),
        lapply(self$`hazard`, function(x) paste(x$toJSON(), sep=",")),
        self$`generalComment`,
        self$`temporalInformation`,
        lapply(self$`spatialInformation`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(PredictiveModelScopeJson) {
      PredictiveModelScopeObject <- jsonlite::fromJSON(PredictiveModelScopeJson)
      self$`product` <- lapply(PredictiveModelScopeObject$`product`, function(x) PredictiveModelScopeProduct$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`hazard` <- lapply(PredictiveModelScopeObject$`hazard`, function(x) Hazard$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
      self$`generalComment` <- PredictiveModelScopeObject$`generalComment`
      self$`temporalInformation` <- PredictiveModelScopeObject$`temporalInformation`
      self$`spatialInformation` <- PredictiveModelScopeObject$`spatialInformation`
    }
  )
)
