# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' QualityMeasures Class
#'
#' @field SSE 
#' @field MSE 
#' @field RMSE 
#' @field RSquared 
#' @field AIC 
#' @field BIC 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
QualityMeasures <- R6::R6Class(
  'QualityMeasures',
  public = list(
    `SSE` = NULL,
    `MSE` = NULL,
    `RMSE` = NULL,
    `RSquared` = NULL,
    `AIC` = NULL,
    `BIC` = NULL,
    initialize = function(`SSE`, `MSE`, `RMSE`, `RSquared`, `AIC`, `BIC`){
      if (!missing(`SSE`)) {
        stopifnot(is.numeric(`SSE`), length(`SSE`) == 1)
        self$`SSE` <- `SSE`
      }
      if (!missing(`MSE`)) {
        stopifnot(is.numeric(`MSE`), length(`MSE`) == 1)
        self$`MSE` <- `MSE`
      }
      if (!missing(`RMSE`)) {
        stopifnot(is.numeric(`RMSE`), length(`RMSE`) == 1)
        self$`RMSE` <- `RMSE`
      }
      if (!missing(`RSquared`)) {
        stopifnot(is.numeric(`RSquared`), length(`RSquared`) == 1)
        self$`RSquared` <- `RSquared`
      }
      if (!missing(`AIC`)) {
        stopifnot(is.numeric(`AIC`), length(`AIC`) == 1)
        self$`AIC` <- `AIC`
      }
      if (!missing(`BIC`)) {
        stopifnot(is.numeric(`BIC`), length(`BIC`) == 1)
        self$`BIC` <- `BIC`
      }
    },
    toJSON = function() {
      QualityMeasuresObject <- list()
      if (!is.null(self$`SSE`)) {
        QualityMeasuresObject[['SSE']] <- self$`SSE`
      }
      if (!is.null(self$`MSE`)) {
        QualityMeasuresObject[['MSE']] <- self$`MSE`
      }
      if (!is.null(self$`RMSE`)) {
        QualityMeasuresObject[['RMSE']] <- self$`RMSE`
      }
      if (!is.null(self$`RSquared`)) {
        QualityMeasuresObject[['RSquared']] <- self$`RSquared`
      }
      if (!is.null(self$`AIC`)) {
        QualityMeasuresObject[['AIC']] <- self$`AIC`
      }
      if (!is.null(self$`BIC`)) {
        QualityMeasuresObject[['BIC']] <- self$`BIC`
      }

      QualityMeasuresObject
    },
    fromJSON = function(QualityMeasuresJson) {
      QualityMeasuresObject <- jsonlite::fromJSON(QualityMeasuresJson)
      if (!is.null(QualityMeasuresObject$`SSE`)) {
        self$`SSE` <- QualityMeasuresObject$`SSE`
      }
      if (!is.null(QualityMeasuresObject$`MSE`)) {
        self$`MSE` <- QualityMeasuresObject$`MSE`
      }
      if (!is.null(QualityMeasuresObject$`RMSE`)) {
        self$`RMSE` <- QualityMeasuresObject$`RMSE`
      }
      if (!is.null(QualityMeasuresObject$`RSquared`)) {
        self$`RSquared` <- QualityMeasuresObject$`RSquared`
      }
      if (!is.null(QualityMeasuresObject$`AIC`)) {
        self$`AIC` <- QualityMeasuresObject$`AIC`
      }
      if (!is.null(QualityMeasuresObject$`BIC`)) {
        self$`BIC` <- QualityMeasuresObject$`BIC`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "SSE": %d,
           "MSE": %d,
           "RMSE": %d,
           "RSquared": %d,
           "AIC": %d,
           "BIC": %d
        }',
        self$`SSE`,
        self$`MSE`,
        self$`RMSE`,
        self$`RSquared`,
        self$`AIC`,
        self$`BIC`
      )
    },
    fromJSONString = function(QualityMeasuresJson) {
      QualityMeasuresObject <- jsonlite::fromJSON(QualityMeasuresJson)
      self$`SSE` <- QualityMeasuresObject$`SSE`
      self$`MSE` <- QualityMeasuresObject$`MSE`
      self$`RMSE` <- QualityMeasuresObject$`RMSE`
      self$`RSquared` <- QualityMeasuresObject$`RSquared`
      self$`AIC` <- QualityMeasuresObject$`AIC`
      self$`BIC` <- QualityMeasuresObject$`BIC`
    }
  )
)
