# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Reference Class
#'
#' @field isReferenceDescription 
#' @field type 
#' @field date 
#' @field pmid 
#' @field doi 
#' @field authorList 
#' @field title 
#' @field abstract 
#' @field journal 
#' @field volume 
#' @field issue 
#' @field status 
#' @field website 
#' @field comment 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Reference <- R6::R6Class(
  'Reference',
  public = list(
    `isReferenceDescription` = NULL,
    `type` = NULL,
    `date` = NULL,
    `pmid` = NULL,
    `doi` = NULL,
    `authorList` = NULL,
    `title` = NULL,
    `abstract` = NULL,
    `journal` = NULL,
    `volume` = NULL,
    `issue` = NULL,
    `status` = NULL,
    `website` = NULL,
    `comment` = NULL,
    initialize = function(`isReferenceDescription`, `type`, `date`, `pmid`, `doi`, `authorList`, `title`, `abstract`, `journal`, `volume`, `issue`, `status`, `website`, `comment`){
      if (!missing(`isReferenceDescription`)) {
        self$`isReferenceDescription` <- `isReferenceDescription`
      }
      if (!missing(`type`)) {
        stopifnot(is.list(`type`), length(`type`) != 0)
        lapply(`type`, function(x) stopifnot(is.character(x)))
        self$`type` <- `type`
      }
      if (!missing(`date`)) {
        stopifnot(is.character(`date`), length(`date`) == 1)
        self$`date` <- `date`
      }
      if (!missing(`pmid`)) {
        stopifnot(is.character(`pmid`), length(`pmid`) == 1)
        self$`pmid` <- `pmid`
      }
      if (!missing(`doi`)) {
        stopifnot(is.character(`doi`), length(`doi`) == 1)
        self$`doi` <- `doi`
      }
      if (!missing(`authorList`)) {
        stopifnot(is.character(`authorList`), length(`authorList`) == 1)
        self$`authorList` <- `authorList`
      }
      if (!missing(`title`)) {
        stopifnot(is.character(`title`), length(`title`) == 1)
        self$`title` <- `title`
      }
      if (!missing(`abstract`)) {
        stopifnot(is.character(`abstract`), length(`abstract`) == 1)
        self$`abstract` <- `abstract`
      }
      if (!missing(`journal`)) {
        stopifnot(is.character(`journal`), length(`journal`) == 1)
        self$`journal` <- `journal`
      }
      if (!missing(`volume`)) {
        stopifnot(is.character(`volume`), length(`volume`) == 1)
        self$`volume` <- `volume`
      }
      if (!missing(`issue`)) {
        stopifnot(is.character(`issue`), length(`issue`) == 1)
        self$`issue` <- `issue`
      }
      if (!missing(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
      if (!missing(`website`)) {
        stopifnot(is.character(`website`), length(`website`) == 1)
        self$`website` <- `website`
      }
      if (!missing(`comment`)) {
        stopifnot(is.character(`comment`), length(`comment`) == 1)
        self$`comment` <- `comment`
      }
    },
    toJSON = function() {
      ReferenceObject <- list()
      if (!is.null(self$`isReferenceDescription`)) {
        ReferenceObject[['isReferenceDescription']] <- self$`isReferenceDescription`
      }
      if (!is.null(self$`type`)) {
        ReferenceObject[['type']] <- self$`type`
      }
      if (!is.null(self$`date`)) {
        ReferenceObject[['date']] <- self$`date`
      }
      if (!is.null(self$`pmid`)) {
        ReferenceObject[['pmid']] <- self$`pmid`
      }
      if (!is.null(self$`doi`)) {
        ReferenceObject[['doi']] <- self$`doi`
      }
      if (!is.null(self$`authorList`)) {
        ReferenceObject[['authorList']] <- self$`authorList`
      }
      if (!is.null(self$`title`)) {
        ReferenceObject[['title']] <- self$`title`
      }
      if (!is.null(self$`abstract`)) {
        ReferenceObject[['abstract']] <- self$`abstract`
      }
      if (!is.null(self$`journal`)) {
        ReferenceObject[['journal']] <- self$`journal`
      }
      if (!is.null(self$`volume`)) {
        ReferenceObject[['volume']] <- self$`volume`
      }
      if (!is.null(self$`issue`)) {
        ReferenceObject[['issue']] <- self$`issue`
      }
      if (!is.null(self$`status`)) {
        ReferenceObject[['status']] <- self$`status`
      }
      if (!is.null(self$`website`)) {
        ReferenceObject[['website']] <- self$`website`
      }
      if (!is.null(self$`comment`)) {
        ReferenceObject[['comment']] <- self$`comment`
      }

      ReferenceObject
    },
    fromJSON = function(ReferenceJson) {
      ReferenceObject <- jsonlite::fromJSON(ReferenceJson)
      if (!is.null(ReferenceObject$`isReferenceDescription`)) {
        self$`isReferenceDescription` <- ReferenceObject$`isReferenceDescription`
      }
      if (!is.null(ReferenceObject$`type`)) {
        self$`type` <- ReferenceObject$`type`
      }
      if (!is.null(ReferenceObject$`date`)) {
        self$`date` <- ReferenceObject$`date`
      }
      if (!is.null(ReferenceObject$`pmid`)) {
        self$`pmid` <- ReferenceObject$`pmid`
      }
      if (!is.null(ReferenceObject$`doi`)) {
        self$`doi` <- ReferenceObject$`doi`
      }
      if (!is.null(ReferenceObject$`authorList`)) {
        self$`authorList` <- ReferenceObject$`authorList`
      }
      if (!is.null(ReferenceObject$`title`)) {
        self$`title` <- ReferenceObject$`title`
      }
      if (!is.null(ReferenceObject$`abstract`)) {
        self$`abstract` <- ReferenceObject$`abstract`
      }
      if (!is.null(ReferenceObject$`journal`)) {
        self$`journal` <- ReferenceObject$`journal`
      }
      if (!is.null(ReferenceObject$`volume`)) {
        self$`volume` <- ReferenceObject$`volume`
      }
      if (!is.null(ReferenceObject$`issue`)) {
        self$`issue` <- ReferenceObject$`issue`
      }
      if (!is.null(ReferenceObject$`status`)) {
        self$`status` <- ReferenceObject$`status`
      }
      if (!is.null(ReferenceObject$`website`)) {
        self$`website` <- ReferenceObject$`website`
      }
      if (!is.null(ReferenceObject$`comment`)) {
        self$`comment` <- ReferenceObject$`comment`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "isReferenceDescription": %s,
           "type": [%s],
           "date": %s,
           "pmid": %s,
           "doi": %s,
           "authorList": %s,
           "title": %s,
           "abstract": %s,
           "journal": %s,
           "volume": %s,
           "issue": %s,
           "status": %s,
           "website": %s,
           "comment": %s
        }',
        self$`isReferenceDescription`,
        lapply(self$`type`, function(x) paste(paste0('"', x, '"'), sep=",")),
        self$`date`,
        self$`pmid`,
        self$`doi`,
        self$`authorList`,
        self$`title`,
        self$`abstract`,
        self$`journal`,
        self$`volume`,
        self$`issue`,
        self$`status`,
        self$`website`,
        self$`comment`
      )
    },
    fromJSONString = function(ReferenceJson) {
      ReferenceObject <- jsonlite::fromJSON(ReferenceJson)
      self$`isReferenceDescription` <- ReferenceObject$`isReferenceDescription`
      self$`type` <- ReferenceObject$`type`
      self$`date` <- ReferenceObject$`date`
      self$`pmid` <- ReferenceObject$`pmid`
      self$`doi` <- ReferenceObject$`doi`
      self$`authorList` <- ReferenceObject$`authorList`
      self$`title` <- ReferenceObject$`title`
      self$`abstract` <- ReferenceObject$`abstract`
      self$`journal` <- ReferenceObject$`journal`
      self$`volume` <- ReferenceObject$`volume`
      self$`issue` <- ReferenceObject$`issue`
      self$`status` <- ReferenceObject$`status`
      self$`website` <- ReferenceObject$`website`
      self$`comment` <- ReferenceObject$`comment`
    }
  )
)
