# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' Study Class
#'
#' @field identifier 
#' @field title 
#' @field description 
#' @field designType 
#' @field assayMeasurementType 
#' @field assayTechnologyType 
#' @field assayTechnologyPlatform 
#' @field assayTechnologyTypePlatform 
#' @field accreditationProcedureForTheAssayTechnology 
#' @field protocolName 
#' @field protocolType 
#' @field protocolDescription 
#' @field protocolURI 
#' @field protocolVersion 
#' @field protocolParametersName 
#' @field protocolComponentsName 
#' @field protocolComponentsType 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Study <- R6::R6Class(
  'Study',
  public = list(
    `identifier` = NULL,
    `title` = NULL,
    `description` = NULL,
    `designType` = NULL,
    `assayMeasurementType` = NULL,
    `assayTechnologyType` = NULL,
    `assayTechnologyPlatform` = NULL,
    `assayTechnologyTypePlatform` = NULL,
    `accreditationProcedureForTheAssayTechnology` = NULL,
    `protocolName` = NULL,
    `protocolType` = NULL,
    `protocolDescription` = NULL,
    `protocolURI` = NULL,
    `protocolVersion` = NULL,
    `protocolParametersName` = NULL,
    `protocolComponentsName` = NULL,
    `protocolComponentsType` = NULL,
    initialize = function(`identifier`, `title`, `description`, `designType`, `assayMeasurementType`, `assayTechnologyType`, `assayTechnologyPlatform`, `assayTechnologyTypePlatform`, `accreditationProcedureForTheAssayTechnology`, `protocolName`, `protocolType`, `protocolDescription`, `protocolURI`, `protocolVersion`, `protocolParametersName`, `protocolComponentsName`, `protocolComponentsType`){
      if (!missing(`identifier`)) {
        stopifnot(is.character(`identifier`), length(`identifier`) == 1)
        self$`identifier` <- `identifier`
      }
      if (!missing(`title`)) {
        stopifnot(is.character(`title`), length(`title`) == 1)
        self$`title` <- `title`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`designType`)) {
        stopifnot(is.character(`designType`), length(`designType`) == 1)
        self$`designType` <- `designType`
      }
      if (!missing(`assayMeasurementType`)) {
        stopifnot(is.character(`assayMeasurementType`), length(`assayMeasurementType`) == 1)
        self$`assayMeasurementType` <- `assayMeasurementType`
      }
      if (!missing(`assayTechnologyType`)) {
        stopifnot(is.character(`assayTechnologyType`), length(`assayTechnologyType`) == 1)
        self$`assayTechnologyType` <- `assayTechnologyType`
      }
      if (!missing(`assayTechnologyPlatform`)) {
        stopifnot(is.character(`assayTechnologyPlatform`), length(`assayTechnologyPlatform`) == 1)
        self$`assayTechnologyPlatform` <- `assayTechnologyPlatform`
      }
      if (!missing(`assayTechnologyTypePlatform`)) {
        stopifnot(is.character(`assayTechnologyTypePlatform`), length(`assayTechnologyTypePlatform`) == 1)
        self$`assayTechnologyTypePlatform` <- `assayTechnologyTypePlatform`
      }
      if (!missing(`accreditationProcedureForTheAssayTechnology`)) {
        stopifnot(is.character(`accreditationProcedureForTheAssayTechnology`), length(`accreditationProcedureForTheAssayTechnology`) == 1)
        self$`accreditationProcedureForTheAssayTechnology` <- `accreditationProcedureForTheAssayTechnology`
      }
      if (!missing(`protocolName`)) {
        stopifnot(is.character(`protocolName`), length(`protocolName`) == 1)
        self$`protocolName` <- `protocolName`
      }
      if (!missing(`protocolType`)) {
        stopifnot(is.character(`protocolType`), length(`protocolType`) == 1)
        self$`protocolType` <- `protocolType`
      }
      if (!missing(`protocolDescription`)) {
        stopifnot(is.character(`protocolDescription`), length(`protocolDescription`) == 1)
        self$`protocolDescription` <- `protocolDescription`
      }
      if (!missing(`protocolURI`)) {
        stopifnot(is.character(`protocolURI`), length(`protocolURI`) == 1)
        self$`protocolURI` <- `protocolURI`
      }
      if (!missing(`protocolVersion`)) {
        stopifnot(is.character(`protocolVersion`), length(`protocolVersion`) == 1)
        self$`protocolVersion` <- `protocolVersion`
      }
      if (!missing(`protocolParametersName`)) {
        stopifnot(is.character(`protocolParametersName`), length(`protocolParametersName`) == 1)
        self$`protocolParametersName` <- `protocolParametersName`
      }
      if (!missing(`protocolComponentsName`)) {
        stopifnot(is.character(`protocolComponentsName`), length(`protocolComponentsName`) == 1)
        self$`protocolComponentsName` <- `protocolComponentsName`
      }
      if (!missing(`protocolComponentsType`)) {
        stopifnot(is.character(`protocolComponentsType`), length(`protocolComponentsType`) == 1)
        self$`protocolComponentsType` <- `protocolComponentsType`
      }
    },
    toJSON = function() {
      StudyObject <- list()
      if (!is.null(self$`identifier`)) {
        StudyObject[['identifier']] <- self$`identifier`
      }
      if (!is.null(self$`title`)) {
        StudyObject[['title']] <- self$`title`
      }
      if (!is.null(self$`description`)) {
        StudyObject[['description']] <- self$`description`
      }
      if (!is.null(self$`designType`)) {
        StudyObject[['designType']] <- self$`designType`
      }
      if (!is.null(self$`assayMeasurementType`)) {
        StudyObject[['assayMeasurementType']] <- self$`assayMeasurementType`
      }
      if (!is.null(self$`assayTechnologyType`)) {
        StudyObject[['assayTechnologyType']] <- self$`assayTechnologyType`
      }
      if (!is.null(self$`assayTechnologyPlatform`)) {
        StudyObject[['assayTechnologyPlatform']] <- self$`assayTechnologyPlatform`
      }
      if (!is.null(self$`assayTechnologyTypePlatform`)) {
        StudyObject[['assayTechnologyTypePlatform']] <- self$`assayTechnologyTypePlatform`
      }
      if (!is.null(self$`accreditationProcedureForTheAssayTechnology`)) {
        StudyObject[['accreditationProcedureForTheAssayTechnology']] <- self$`accreditationProcedureForTheAssayTechnology`
      }
      if (!is.null(self$`protocolName`)) {
        StudyObject[['protocolName']] <- self$`protocolName`
      }
      if (!is.null(self$`protocolType`)) {
        StudyObject[['protocolType']] <- self$`protocolType`
      }
      if (!is.null(self$`protocolDescription`)) {
        StudyObject[['protocolDescription']] <- self$`protocolDescription`
      }
      if (!is.null(self$`protocolURI`)) {
        StudyObject[['protocolURI']] <- self$`protocolURI`
      }
      if (!is.null(self$`protocolVersion`)) {
        StudyObject[['protocolVersion']] <- self$`protocolVersion`
      }
      if (!is.null(self$`protocolParametersName`)) {
        StudyObject[['protocolParametersName']] <- self$`protocolParametersName`
      }
      if (!is.null(self$`protocolComponentsName`)) {
        StudyObject[['protocolComponentsName']] <- self$`protocolComponentsName`
      }
      if (!is.null(self$`protocolComponentsType`)) {
        StudyObject[['protocolComponentsType']] <- self$`protocolComponentsType`
      }

      StudyObject
    },
    fromJSON = function(StudyJson) {
      StudyObject <- jsonlite::fromJSON(StudyJson)
      if (!is.null(StudyObject$`identifier`)) {
        self$`identifier` <- StudyObject$`identifier`
      }
      if (!is.null(StudyObject$`title`)) {
        self$`title` <- StudyObject$`title`
      }
      if (!is.null(StudyObject$`description`)) {
        self$`description` <- StudyObject$`description`
      }
      if (!is.null(StudyObject$`designType`)) {
        self$`designType` <- StudyObject$`designType`
      }
      if (!is.null(StudyObject$`assayMeasurementType`)) {
        self$`assayMeasurementType` <- StudyObject$`assayMeasurementType`
      }
      if (!is.null(StudyObject$`assayTechnologyType`)) {
        self$`assayTechnologyType` <- StudyObject$`assayTechnologyType`
      }
      if (!is.null(StudyObject$`assayTechnologyPlatform`)) {
        self$`assayTechnologyPlatform` <- StudyObject$`assayTechnologyPlatform`
      }
      if (!is.null(StudyObject$`assayTechnologyTypePlatform`)) {
        self$`assayTechnologyTypePlatform` <- StudyObject$`assayTechnologyTypePlatform`
      }
      if (!is.null(StudyObject$`accreditationProcedureForTheAssayTechnology`)) {
        self$`accreditationProcedureForTheAssayTechnology` <- StudyObject$`accreditationProcedureForTheAssayTechnology`
      }
      if (!is.null(StudyObject$`protocolName`)) {
        self$`protocolName` <- StudyObject$`protocolName`
      }
      if (!is.null(StudyObject$`protocolType`)) {
        self$`protocolType` <- StudyObject$`protocolType`
      }
      if (!is.null(StudyObject$`protocolDescription`)) {
        self$`protocolDescription` <- StudyObject$`protocolDescription`
      }
      if (!is.null(StudyObject$`protocolURI`)) {
        self$`protocolURI` <- StudyObject$`protocolURI`
      }
      if (!is.null(StudyObject$`protocolVersion`)) {
        self$`protocolVersion` <- StudyObject$`protocolVersion`
      }
      if (!is.null(StudyObject$`protocolParametersName`)) {
        self$`protocolParametersName` <- StudyObject$`protocolParametersName`
      }
      if (!is.null(StudyObject$`protocolComponentsName`)) {
        self$`protocolComponentsName` <- StudyObject$`protocolComponentsName`
      }
      if (!is.null(StudyObject$`protocolComponentsType`)) {
        self$`protocolComponentsType` <- StudyObject$`protocolComponentsType`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "identifier": %s,
           "title": %s,
           "description": %s,
           "designType": %s,
           "assayMeasurementType": %s,
           "assayTechnologyType": %s,
           "assayTechnologyPlatform": %s,
           "assayTechnologyTypePlatform": %s,
           "accreditationProcedureForTheAssayTechnology": %s,
           "protocolName": %s,
           "protocolType": %s,
           "protocolDescription": %s,
           "protocolURI": %s,
           "protocolVersion": %s,
           "protocolParametersName": %s,
           "protocolComponentsName": %s,
           "protocolComponentsType": %s
        }',
        self$`identifier`,
        self$`title`,
        self$`description`,
        self$`designType`,
        self$`assayMeasurementType`,
        self$`assayTechnologyType`,
        self$`assayTechnologyPlatform`,
        self$`assayTechnologyTypePlatform`,
        self$`accreditationProcedureForTheAssayTechnology`,
        self$`protocolName`,
        self$`protocolType`,
        self$`protocolDescription`,
        self$`protocolURI`,
        self$`protocolVersion`,
        self$`protocolParametersName`,
        self$`protocolComponentsName`,
        self$`protocolComponentsType`
      )
    },
    fromJSONString = function(StudyJson) {
      StudyObject <- jsonlite::fromJSON(StudyJson)
      self$`identifier` <- StudyObject$`identifier`
      self$`title` <- StudyObject$`title`
      self$`description` <- StudyObject$`description`
      self$`designType` <- StudyObject$`designType`
      self$`assayMeasurementType` <- StudyObject$`assayMeasurementType`
      self$`assayTechnologyType` <- StudyObject$`assayTechnologyType`
      self$`assayTechnologyPlatform` <- StudyObject$`assayTechnologyPlatform`
      self$`assayTechnologyTypePlatform` <- StudyObject$`assayTechnologyTypePlatform`
      self$`accreditationProcedureForTheAssayTechnology` <- StudyObject$`accreditationProcedureForTheAssayTechnology`
      self$`protocolName` <- StudyObject$`protocolName`
      self$`protocolType` <- StudyObject$`protocolType`
      self$`protocolDescription` <- StudyObject$`protocolDescription`
      self$`protocolURI` <- StudyObject$`protocolURI`
      self$`protocolVersion` <- StudyObject$`protocolVersion`
      self$`protocolParametersName` <- StudyObject$`protocolParametersName`
      self$`protocolComponentsName` <- StudyObject$`protocolComponentsName`
      self$`protocolComponentsType` <- StudyObject$`protocolComponentsType`
    }
  )
)
