# RAKIP Generic model
#
# TODO
#
# OpenAPI spec version: 1.0.4
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git


#' StudySample Class
#'
#' @field sampleName 
#' @field protocolOfSampleCollection 
#' @field samplingStrategy 
#' @field typeOfSamplingProgram 
#' @field samplingMethod 
#' @field samplingPlan 
#' @field samplingWeight 
#' @field samplingSize 
#' @field lotSizeUnit 
#' @field samplingPoint 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StudySample <- R6::R6Class(
  'StudySample',
  public = list(
    `sampleName` = NULL,
    `protocolOfSampleCollection` = NULL,
    `samplingStrategy` = NULL,
    `typeOfSamplingProgram` = NULL,
    `samplingMethod` = NULL,
    `samplingPlan` = NULL,
    `samplingWeight` = NULL,
    `samplingSize` = NULL,
    `lotSizeUnit` = NULL,
    `samplingPoint` = NULL,
    initialize = function(`sampleName`, `protocolOfSampleCollection`, `samplingStrategy`, `typeOfSamplingProgram`, `samplingMethod`, `samplingPlan`, `samplingWeight`, `samplingSize`, `lotSizeUnit`, `samplingPoint`){
      if (!missing(`sampleName`)) {
        stopifnot(is.character(`sampleName`), length(`sampleName`) == 1)
        self$`sampleName` <- `sampleName`
      }
      if (!missing(`protocolOfSampleCollection`)) {
        stopifnot(is.character(`protocolOfSampleCollection`), length(`protocolOfSampleCollection`) == 1)
        self$`protocolOfSampleCollection` <- `protocolOfSampleCollection`
      }
      if (!missing(`samplingStrategy`)) {
        stopifnot(is.character(`samplingStrategy`), length(`samplingStrategy`) == 1)
        self$`samplingStrategy` <- `samplingStrategy`
      }
      if (!missing(`typeOfSamplingProgram`)) {
        stopifnot(is.character(`typeOfSamplingProgram`), length(`typeOfSamplingProgram`) == 1)
        self$`typeOfSamplingProgram` <- `typeOfSamplingProgram`
      }
      if (!missing(`samplingMethod`)) {
        stopifnot(is.character(`samplingMethod`), length(`samplingMethod`) == 1)
        self$`samplingMethod` <- `samplingMethod`
      }
      if (!missing(`samplingPlan`)) {
        stopifnot(is.character(`samplingPlan`), length(`samplingPlan`) == 1)
        self$`samplingPlan` <- `samplingPlan`
      }
      if (!missing(`samplingWeight`)) {
        stopifnot(is.character(`samplingWeight`), length(`samplingWeight`) == 1)
        self$`samplingWeight` <- `samplingWeight`
      }
      if (!missing(`samplingSize`)) {
        stopifnot(is.character(`samplingSize`), length(`samplingSize`) == 1)
        self$`samplingSize` <- `samplingSize`
      }
      if (!missing(`lotSizeUnit`)) {
        stopifnot(is.character(`lotSizeUnit`), length(`lotSizeUnit`) == 1)
        self$`lotSizeUnit` <- `lotSizeUnit`
      }
      if (!missing(`samplingPoint`)) {
        stopifnot(is.character(`samplingPoint`), length(`samplingPoint`) == 1)
        self$`samplingPoint` <- `samplingPoint`
      }
    },
    toJSON = function() {
      StudySampleObject <- list()
      if (!is.null(self$`sampleName`)) {
        StudySampleObject[['sampleName']] <- self$`sampleName`
      }
      if (!is.null(self$`protocolOfSampleCollection`)) {
        StudySampleObject[['protocolOfSampleCollection']] <- self$`protocolOfSampleCollection`
      }
      if (!is.null(self$`samplingStrategy`)) {
        StudySampleObject[['samplingStrategy']] <- self$`samplingStrategy`
      }
      if (!is.null(self$`typeOfSamplingProgram`)) {
        StudySampleObject[['typeOfSamplingProgram']] <- self$`typeOfSamplingProgram`
      }
      if (!is.null(self$`samplingMethod`)) {
        StudySampleObject[['samplingMethod']] <- self$`samplingMethod`
      }
      if (!is.null(self$`samplingPlan`)) {
        StudySampleObject[['samplingPlan']] <- self$`samplingPlan`
      }
      if (!is.null(self$`samplingWeight`)) {
        StudySampleObject[['samplingWeight']] <- self$`samplingWeight`
      }
      if (!is.null(self$`samplingSize`)) {
        StudySampleObject[['samplingSize']] <- self$`samplingSize`
      }
      if (!is.null(self$`lotSizeUnit`)) {
        StudySampleObject[['lotSizeUnit']] <- self$`lotSizeUnit`
      }
      if (!is.null(self$`samplingPoint`)) {
        StudySampleObject[['samplingPoint']] <- self$`samplingPoint`
      }

      StudySampleObject
    },
    fromJSON = function(StudySampleJson) {
      StudySampleObject <- jsonlite::fromJSON(StudySampleJson)
      if (!is.null(StudySampleObject$`sampleName`)) {
        self$`sampleName` <- StudySampleObject$`sampleName`
      }
      if (!is.null(StudySampleObject$`protocolOfSampleCollection`)) {
        self$`protocolOfSampleCollection` <- StudySampleObject$`protocolOfSampleCollection`
      }
      if (!is.null(StudySampleObject$`samplingStrategy`)) {
        self$`samplingStrategy` <- StudySampleObject$`samplingStrategy`
      }
      if (!is.null(StudySampleObject$`typeOfSamplingProgram`)) {
        self$`typeOfSamplingProgram` <- StudySampleObject$`typeOfSamplingProgram`
      }
      if (!is.null(StudySampleObject$`samplingMethod`)) {
        self$`samplingMethod` <- StudySampleObject$`samplingMethod`
      }
      if (!is.null(StudySampleObject$`samplingPlan`)) {
        self$`samplingPlan` <- StudySampleObject$`samplingPlan`
      }
      if (!is.null(StudySampleObject$`samplingWeight`)) {
        self$`samplingWeight` <- StudySampleObject$`samplingWeight`
      }
      if (!is.null(StudySampleObject$`samplingSize`)) {
        self$`samplingSize` <- StudySampleObject$`samplingSize`
      }
      if (!is.null(StudySampleObject$`lotSizeUnit`)) {
        self$`lotSizeUnit` <- StudySampleObject$`lotSizeUnit`
      }
      if (!is.null(StudySampleObject$`samplingPoint`)) {
        self$`samplingPoint` <- StudySampleObject$`samplingPoint`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "sampleName": %s,
           "protocolOfSampleCollection": %s,
           "samplingStrategy": %s,
           "typeOfSamplingProgram": %s,
           "samplingMethod": %s,
           "samplingPlan": %s,
           "samplingWeight": %s,
           "samplingSize": %s,
           "lotSizeUnit": %s,
           "samplingPoint": %s
        }',
        self$`sampleName`,
        self$`protocolOfSampleCollection`,
        self$`samplingStrategy`,
        self$`typeOfSamplingProgram`,
        self$`samplingMethod`,
        self$`samplingPlan`,
        self$`samplingWeight`,
        self$`samplingSize`,
        self$`lotSizeUnit`,
        self$`samplingPoint`
      )
    },
    fromJSONString = function(StudySampleJson) {
      StudySampleObject <- jsonlite::fromJSON(StudySampleJson)
      self$`sampleName` <- StudySampleObject$`sampleName`
      self$`protocolOfSampleCollection` <- StudySampleObject$`protocolOfSampleCollection`
      self$`samplingStrategy` <- StudySampleObject$`samplingStrategy`
      self$`typeOfSamplingProgram` <- StudySampleObject$`typeOfSamplingProgram`
      self$`samplingMethod` <- StudySampleObject$`samplingMethod`
      self$`samplingPlan` <- StudySampleObject$`samplingPlan`
      self$`samplingWeight` <- StudySampleObject$`samplingWeight`
      self$`samplingSize` <- StudySampleObject$`samplingSize`
      self$`lotSizeUnit` <- StudySampleObject$`lotSizeUnit`
      self$`samplingPoint` <- StudySampleObject$`samplingPoint`
    }
  )
)
